### ISSUE TITLE
Mudança de geração

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/free-mtrix#10]
A contagem dos ciclos para a mudança de geração estava de acordo com a quantidade de ciclos finalizados na condição, porém a mudança de geração deve ser fixa e ocorrer independente da condição, é contingente à quantidade do total de ciclos que foram finalizados no experimento e não na condição. Por exemplo, se está programado que a cada 10 ciclos deve mudar de geração, caso a condição 1 finalize com 5 ciclos, após 5 ciclos da condição 2 deve mudar de geração. Isso não é zerado quando muda de condição.

**Comment by cpicanco** [comment]
@thaismguimaraes, entendi, mas me diga uma coisa, você imagina que o valor dos ciclos possa mudar em outros experimentos? Por exemplo:

- Condição 1. 10 ciclos.

- Condição 2. 5 ciclos.

**Comment by thaismguimaraes** [comment]
Em um experimento, a quantidade de ciclos para a mudança de geração é fixa, não muda durante as condições. É o que tem sido programado.

**Comment by cpicanco** [comment]
Mas experimentos futuros podem ter esse parâmetro como uma variável?

**Comment by thaismguimaraes** [comment]
Pode ser possível. Se puder deixar isso flexível, pensando em estudos futuros, seria bom.

**Comment by cpicanco** [comment]
6c4a3ef4520e738ca09327a88a323820c4c56e1b
