### ISSUE TITLE
Sugestões do Prof. Emmanuel Z. Tourinho

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/free-mtrix#12]
- [x] "Em vez de falar de pontos de tipo A e B, talvez seja melhor falar de fichas azuis (para respostas impulsivas) e vermelhas (para respostas autocontroladas). Isso pode aparecer assim nos contadores. Nesse caso, a pergunta deve ser: Vocês perderam um item escolar nesta rodada. Vocês gostariam de recuperar esse item escolar, em troca de X fichas azuis?"

- [x] "Como no caso das fichas (e não pontos), é importante que o contador especifique que se trata de itens escolares para doação. Observe que é necessário modificar a interface dos participantes, para que visualizem o Total de Fichas Azuis, o Total de Fichas Vermelhas e o Total de Itens Escolares para Doação."

(Tourinho, comunicação pessoal, fevereiro 05, 2017)

**Comment by cpicanco** [comment]
Vou botar a figura das fichas também.

**Comment by cpicanco** [comment]
Com nomes mais longos achei melhor colocar a pontuação abaixo da matrix.

**Comment by cpicanco** [comment]
@thaismguimaraes confira ai

Sugiro escolher cores que não estão na matrix, só para evitar qualquer confusão...

![screenshot - 02092017 - 09 42 46 pm](https://cloud.githubusercontent.com/assets/6511849/22809417/2320b104-ef11-11e6-8f8f-7aa34ca20160.png)

**Comment by thaismguimaraes** [comment]
Verdade, isso pode interferir no desempenho da tarefa. Imagens das fichas e itens escolares foram encaminhadas para seu e-mail.

**Comment by cpicanco** [comment]
![screenshot - 02102017 - 12 27 13 am](https://cloud.githubusercontent.com/assets/6511849/22813365/d55d0d6e-ef29-11e6-9a4f-ce5ceda6ab46.png)

**Comment by thaismguimaraes** [comment]
@cpicanco ficou ótimo.

**Comment by cpicanco** [comment]
1933c9b7001322b1237bbe7775edfa48170c5e79
