### ISSUE TITLE
Qual o significado das letras na chave Contingência.1.Consequência?

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#14]
![image](https://user-images.githubusercontent.com/22918273/35735253-cacb5d7c-0802-11e8-81d3-73700d32d917.png)

**Comment by cpicanco** [comment]
Por gentileza, sugiro que você escreva ou copie e cole o texto e não imagens de texto neste espaço, pois isso facilitará buscas futuras e agilizará as respostas.
____
O valor da chave `Contingência.1.Consequência=` possui dois campos separados pelo caractere `|`. O primeiro campo `3,0` é o número de pontos e sua variação correspondente, respectivamente. No segundo campo cada letra ativa um aspecto da consequência e a ausência de uma letra desativa o aspecto correspondente. 

Os aspectos possíveis são os seguintes:

https://github.com/lacs-ufpa/free-mtrix/blob/d2d6aa65fe23278891a43ede90e31616b4dd1a88/experiment_runner/units/string_methods.pas#L364-L383

```pascal
      '0':Result+=[gscNone]; // valor sem função
      'M':Result+=[gscMessage]; // habilita a apresentação de uma mensagem para o participante
      'C':Result+=[gscBroadcastMessage]; // habilita a apresentação da mensagem aos outros participantes
      'P':Result+=[gscPoints]; // habilita a contagem de pontuação
      'V':Result+=[gscVariablePoints]; // habilita a variação da pontuação
      'A':Result+=[gscA]; // habilita incremento da pontuação na consequência individual A
      'B':Result+=[gscB]; // habilita incremento da pontuação na consequência individual B
      'G':Result+=[gscG]; // habilita incremento da pontuação na consequência do grupo G
      'I':Result+=[gscI]; // habilita incremento da pontuação na consequência individual I 
```
Versões futuras utilizarão, ao invés de letras, as seguintes expressões:

https://github.com/lacs-ufpa/free-mtrix/blob/31bbd16d3474326b3fe0c7c55091d8eced2d5b81/experiment_runner/units/string_methods.pas#L258-L272

Sugestões são bem vindas.

**Comment by VALDERLON** [comment]
Sobre a primeira questão: Entendido. 

Farei as próximas questões como solicitado.

Obrigado!
