### ISSUE TITLE
Configuração de culturantes com combinações de cores específicas

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#15]
Na versão do programa que estou utilizando (o da Thais), com relação às cores, os culturantes possíveis são "core iguais" ou "cores diferentes".

No meu caso, e do Tide, um culturante precisaria ser especificado na combinação verde+amarelo+qualquer outra cor, e outro culturante na azul+vermelho+qualquer outra cor.

**Comment by cpicanco** [comment]
Teste a versão anexada em #17.
