### ISSUE TITLE
Adição de dois contadores de consequências culturais

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#17]
Necessário adicionar dois contadores de consequências culturais. Um pra cada culturante  programado.

**Comment by cpicanco** [comment]
Tente fazer um arquivo de configuração usando o `Designer` e tente executar o arquivo de configuração usando o `Runner`.
[experiment_designer_windows_64bits_v0.2.0.14-8-g82aeae8.zip](https://github.com/lacs-ufpa/free-mtrix/files/1704283/experiment_designer_windows_64bits_v0.2.0.14-8-g82aeae8.zip)
[experiment_runner_windows_64bits_v0.2.0.14-8-g82aeae8.zip](https://github.com/lacs-ufpa/free-mtrix/files/1704284/experiment_runner_windows_64bits_v0.2.0.14-8-g82aeae8.zip)

**Comment by VALDERLON** [comment]
@cpicanco o experiment_designer_windows_64bits_v0.2.0.14-8-g82aeae8.zip abre e conseguimos fazer as configurações do experimento, contudo o experiment_runner_windows_64bits_v0.2.0.14-8-g82aeae8.zip não abre em nenhum computador que eu testei, mesmo instalando as extensões sugeridas no manual. 

PERGUNTA: Há uma série de pequenos erros, que serão descritos em "issues" independentes em breve. esses erros podem ocorrer, porque estamos montando o experimento no novo designer, mas estamos rodando no runner antigo (o da Thais)?

**Comment by cpicanco** [comment]
As extensões sugeridas estão desatualizadas. Você deve baixar o pacote 2017
C++ redistribuível do site da microsoft para a arquitetura da máquina (32
ou 64 bits).

**Comment by cpicanco** [comment]
Vc pode encontrar os pacotes no site a seguir, Visual Studio 2017.

https://support.microsoft.com/pt-br/help/2977003/the-latest-supported-visual-c-downloads



On Feb 20, 2018 11:53, "Rafael Picanço" <cpicanco42@gmail.com> wrote:

As extensões sugeridas estão desatualizadas. Você deve baixar o pacote 2017
C++ redistribuível do site da microsoft para a arquitetura da máquina (32
ou 64 bits).

**Comment by cpicanco** [comment]
@VALDERLON há uma nova versão em anexo.

[free-mtrix-yan.zip](https://github.com/lacs-ufpa/free-mtrix/files/1773166/free-mtrix-yan.zip)

**Comment by cpicanco** [comment]
@VALDERLON Teste a nova versão do `runner` em anexo. Configure o seu arquivo de sessão adicionando chaves como `Culturante1.Contador.Rótulo=`, seguidas de seu respectivo texto, por exemplo:

```txt
; primeira condição
[Condição.1]

; rótulo do contador do culturante 1
Culturante1.Contador.Rótulo=Atraso\n1

; rótulo do contador do culturante 2
Culturante2.Contador.Rótulo=Atraso\n2

; segunda condição
[Condição.2]
Culturante1.Contador.Rótulo=Atraso 3
Culturante2.Contador.Rótulo=Atraso 4

; e assim por diante [Condição.3]
```

Note o código `\n` nos dois primeiros casos, ele serve para a quebra do texto em linhas, caso o texto seja longo.

[experiment_runner_windows_32bits_v0.2.0.14-16-g9e59884.zip](https://github.com/lacs-ufpa/free-mtrix/files/1826718/experiment_runner_windows_32bits_v0.2.0.14-16-g9e59884.zip)

**Comment by VALDERLON** [comment]
@cpicanco Obrigado pelos updates. 
Só uma dúvida, essa alteração a gente faz diretamente no arquivo de texto, correto? Eu queria saber exatamente onde adicionamos esse novo comando. Digo, entre quais linhas do arquivo de texto. Segue o exemplo da minha primeira condição.

(primeira tentativa - novas linhas destacadas em negrito)
[Condição.1]
Nome=A1 - Linha de base Magnitude
Rodada.NúmeroDeJogadores=3
Rodada.OrdemDeJogadaAleatória=1
Pontos.Somar_ao_iniciar_condição.A=0
Pontos.Somar_ao_iniciar_condição.B=0
Pontos.Somar_ao_iniciar_condição.I=0
Pontos.Somar_ao_iniciar_condição.G1=0
Pontos.Somar_ao_iniciar_condição.G2=0
Ciclos.MudançaDeGeração=70
Critério_de_Finalização.Estilo=O QUE OCORRER PRIMEIRO
Critério_de_Finalização.Ciclos=10
Critério_de_Finalização.Porcentagem=80,5
**Culturante1.Contador.Rótulo=ITENS DOADOS DAQUI A 01 DIA
Culturante2.Contador.Rótulo=ITENS DOADOS DAQUI A 01 DIA**
Contingência.1.Nome=Operante Impar A1
Contingência.1.Resposta=IMPAR,|LINHAS||
Contingência.1.Consequência=3,0|M,C,P,I,
Contingência.1.Consequência.Mensagem.Prefixo=$NICNAME ganhou 3 fichas.
Contingência.1.Consequência.Mensagem.Prefixo_ao_perder=
Contingência.1.Consequência.Mensagem.Sufixo_ao_perder.Singular=
Contingência.1.Consequência.Mensagem.Sufixo_ao_perder.Plural=
Contingência.1.Consequência.Mensagem.Prefixo_ao_ganhar=
Contingência.1.Consequência.Mensagem.Sufixo_ao_ganhar.Singular=
Contingência.1.Consequência.Mensagem.Sufixo_ao_ganhar.Plural=
Contingência.1.Consequência.Mensagem.Sufixo_zero=
Contingência.2.Nome=Operante par A1
Contingência.2.Resposta=IMPAR,|LINHAS||
Contingência.2.Consequência=1,0|M,C,P,
Contingência.2.Consequência.Mensagem.Prefixo=$NICNAME ganhou 1 ficha.
Metacontingência.1.Nome=Culturante impulsivo 1A1
Metacontingência.1.Resposta=|CORES|AMARELO,VERDE,ROXO,ESPECIFICAMENTE,|
Metacontingência.1.Consequência=1,0|M,C,P,G1,
Metacontingência.1.Consequência.Mensagem.Prefixo=Vocês produziram 1 ITEM escolar que será doado uma creche pública de Belém.
Metacontingência.1.Consequência.Mensagem.Prefixo_ao_perder=
Metacontingência.1.Consequência.Mensagem.Sufixo_ao_perder.Singular=
Metacontingência.1.Consequência.Mensagem.Sufixo_ao_perder.Plural=
Metacontingência.1.Consequência.Mensagem.Prefixo_ao_ganhar=
Metacontingência.1.Consequência.Mensagem.Sufixo_ao_ganhar.Singular=
Metacontingência.1.Consequência.Mensagem.Sufixo_ao_ganhar.Plural=
Metacontingência.1.Consequência.Mensagem.Sufixo_zero=
Metacontingência.2.Nome=Culturante impulsivo 2A1
Metacontingência.2.Resposta=|CORES|AMARELO,VERMELHO,VERDE,ESPECIFICAMENTE,|
Metacontingência.2.Consequência=1,0|M,C,P,G1,
Metacontingência.2.Consequência.Mensagem.Prefixo=Vocês produziram 1 ITEM escolar que será doado uma creche pública de Belém.
Metacontingência.3.Nome=Culturante impulsivo 3A1
Metacontingência.3.Resposta=|CORES|AMARELO,VERDE,AZUL,ESPECIFICAMENTE,|
Metacontingência.3.Consequência=1,0|M,C,P,G1,
Metacontingência.3.Consequência.Mensagem.Prefixo=Vocês produziram 1 ITEM escolar que será doado uma creche pública de Belém.
Metacontingência.4.Nome=Culturante autocontrolado 1A1
Metacontingência.4.Resposta=|CORES|VERMELHO,AZUL,ROXO,ESPECIFICAMENTE,|
Metacontingência.4.Consequência=10,0|M,C,P,G2,
Metacontingência.4.Consequência.Mensagem.Prefixo=Vocês produziram 10 ITENS escolares que serão doados uma creche pública de Belém.
Metacontingência.5.Nome=Culturante autocontrolado 2A1
Metacontingência.5.Resposta=|CORES|AMARELO,VERMELHO,AZUL,ESPECIFICAMENTE,|
Metacontingência.5.Consequência=10,0|M,C,P,G2,
Metacontingência.5.Consequência.Mensagem.Prefixo=Vocês produziram 10 ITENS escolares que serão doados uma creche pública de Belém.
Metacontingência.6.Nome=Culturante autocontrolado 3A1
Metacontingência.6.Resposta=|CORES|VERMELHO,VERDE,AZUL,ESPECIFICAMENTE,|
Metacontingência.6.Consequência=10,0|M,C,P,G2,
Metacontingência.6.Consequência.Mensagem.Prefixo=Vocês produziram 10 ITENS escolares que serão doados uma creche pública de Belém.
.Resposta=|CORES|AMARELO,VERDE,ROXO,ESPECIFICAMENTE,|
.Consequência.Mensagem.Prefixo=$NICNAME ganhou 3 pontos.
.Consequência.Mensagem.Prefixo_ao_perder=
.Consequência.Mensagem.Sufixo_ao_perder.Singular=
.Consequência.Mensagem.Sufixo_ao_perder.Plural=
.Consequência.Mensagem.Prefixo_ao_ganhar=
.Consequência.Mensagem.Sufixo_ao_ganhar.Singular=
.Consequência.Mensagem.Sufixo_ao_ganhar.Plural=
.Consequência.Mensagem.Sufixo_zero=

Tentamos realizar testes com as linhas de comando em outros locais do texto, porém não modificou nada no runner.

**Comment by cpicanco** [comment]
Vc deve usar a nova versão em anexo. O lugar das novas linhas não importa.
Procure na internet sobre o formato de aquivos INI para mais detalhes sobre
a estrutura do arquivo.

**Comment by tidetomaz** [comment]
Utilizamos o novo runner que você mandou em anexo, fizemos as edições no arquivo de sessão de formato ''.ini'', porém nada aconteceu.

**Comment by tidetomaz** [comment]
@cpicanco fiz novos testes substituindo todos os arquivos pelos novos enviados por você. Deu tudo certo e a mensagem já consta nos contadores à depender da condição programada. Muito obrigado!
