### ISSUE TITLE
Contadores de consequências culturais com variação de magnitude e atraso

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#18]
Ambos os contadores precisam sinalizar: 1) quantidade de ítens produzidos; 2) Atrasos para entrega dos ítens após o experimento. Valores variando de acordo com o culturante e condição programados.

**Comment by cpicanco** [comment]
Magnitude e atraso no seu experimento são controlados por pontos e mensagens de texto, respectivamente. Pontos e mensagens já são possíveis.

**Comment by VALDERLON** [comment]
Correto, há mesmo a pontuação e a mensagem. Mas o atraso precisa ficar sinalizado o tempo inteiro, porque eles precisam de um Sd presente, sinalizando quantas consequências culturais são produzidas pra cada culturante e quando eles serão entregues. Os estudo de autocontrole sempre tem esse Sd. Por exemplo, no caso de animais infra-humanos, quando o animal responde autocontroladamente, ele adiciona um ponto num contador, ou ascende uma luz num painel, alguma coisa que sinaliza que ele produziu X consequências de maior magnitude do que as imediatas, mas só receberá daqui um tempo.

**Comment by cpicanco** [comment]
Sim, você planejou a sinalização por meio de dois contadores, um para cada culturante, correto? Veja #17
