### ISSUE TITLE
Adição de mensagem/imagem no software aos participantes durante o experimento. 

### ISSUE THREAD

**Issue by tidetomaz** [lacs-ufpa/free-mtrix#19]
Existe a possibilidade de que uma mensagem ou imagem fique exposta durante a condição programada sinalizando aos participantes que eles não podem/podem interagir verbalmente entre si? Ex: meu delineamento ABAB, na condição A os participantes podem interagir, na condição B não.

 Agradeço a atenção desde já.

**Comment by cpicanco** [comment]
@tidetomaz 

Sim é possível. Mas tenho uma sugestão. O que você acha de usar a postura de pesquisador (fantasiado de cientista) como "autoridade" para prevenir a fala? Como nos estudos clássicos sobre seguimento de regra sob autoridade. Por exemplo, você pode entrar dentro da sala e anunciar que eles não poderiam conversar, prevenindo ativamente qualquer tipo de comunicação entre os participantes. O programa serviria apenas como um prompt para você entrar ou sair da sala.

**Comment by VALDERLON** [comment]
@cpicanco entendo a sugestão que você deu, mas creio que isso seria uma variável estranha. Nos estudo anteriores, feito "à mão", houve vários momentos em que a presença do experimentador pode ter afetado as respostas dos participantes, muito embora isso seja muito pouco discutido nos trabalhos. Reitero que um dos principais objetivos das coletas informatizadas é justamente amenizar estas variáveis, mas isso não invalida de num futuro a gente testar o efeito da presença/ausência do pesquisador como variável independente.

**Comment by cpicanco** [comment]
Uma variável não é estranha, por definição, se ela é uma variável
dependente. Talvez o que você queira dizer é que outras variáveis estranhas
podem ocorrer. Lembre-se, isso sempre será possível, com ou sem software.
Existem diferentes razões para se usar um programa, mas as vezes o melhor
pode ser fazer manualmente ou, então, automatizar o que for possível e
fazer manualmente o que for necessário.

**Comment by tidetomaz** [comment]
Acho importante considerar as sugestões dadas. Para o controle da interação verbal dos participantes já havíamos pensado algumas variações. Uma das foi o aviso no software durante o experimento. Como você avaliou que existe a possibilidade, como proceder para inserir tal aviso nas condições programadas? Há algum tutorial de modificações no free m-trix?

**Comment by cpicanco** [comment]
Não, não há. Se vc tiver interesse em programação a gente pode ir
construindo, mas já adianto que não será algo trivial para um iniciante.
Existem partes do código que precisam ser reformatadas para maior clareza.
Quando vc irá qualificar?

**Comment by cpicanco** [comment]
Uma outra alternativa é colocar uma placa, daquelas de pendurar com fio.

Condição A. Placa 1.

Condição B. Placa 2.

**Comment by tidetomaz** [comment]
Já havia pensado a questão das placas como uma alternativa para se pensar a sinalização aos participantes pro caso da impossibilidade da notificação via software. Bom saber que outros experimentadores também utilizariam o mesmo como procedimento. Obrigado pelas dicas.

**Comment by tidetomaz** [comment]
Rafael, em relação ao aviso que controlará a interação verbal dos participantes, pensei em projetar imagens na televisão da sala 01 do LACS, os avisos sendo controlados pelo experimentador. De modo que as alterações que pedi à você em relação à adição de imagem no software, no momento, não se farão mais necessárias. Agradeço as sugestões e atenção.
