### ISSUE TITLE
A seleção do campo "Extinção" não permanece

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/free-mtrix#2]
A seleção do campo "Extinção" no "Estilo de Resposta" da metacontingência não permanece ao sair e retornar da aba de "Contingências", sendo modificado para outro Estilo de Resposta que já havia sido delineado, apesar de continuar com o mesmo nome dado à metacontingência. Verificar se isso se aplica no campo "Extinção" da contingência.

**Comment by cpicanco** [comment]
Não consegui replicar o problema aqui.

**Comment by thaismguimaraes** [comment]
Executarei esse  teste novamente.

**Comment by thaismguimaraes** [comment]
Repliquei o problema da não permanecia da seleção do campo "Extinção" no "Estilo de Resposta" da metacontingência e, agora, também de Contingências Operantes. Ocorre somente quando muda a seleção para "Mostrar" Contingências Operantes e retorno para "Mostrar" metacontingência, permanecendo o "Estilo de Resposta" da primeira, e vice-versa. Ele só fica fixo quando a seleção "Extinção" é simultânea para Contingências Operantes e metacontingência.

**Comment by cpicanco** [comment]
Preciso testar isso.

**Comment by thaismguimaraes** [comment]
Testei novamente e ainda permanece esse problema. Chegou a testar?

**Comment by cpicanco** [comment]
Humm, estranho, não consigo replicar aqui.

**Comment by cpicanco** [comment]
@thaismguimaraes , tentei de várias maneiras, mas realmente não consegui. Depois vemos isso juntos.

**Comment by cpicanco** [comment]
Possivelmente resolvido com c27ecf3.

@thaismguimaraes , por favor teste após eu subir uma versão com os consertos.
