### ISSUE TITLE
Utilização novo RUNNER

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#20]
O novo runner não abre e aparecia a seguinte mensagem: "O programa não pode ser iniciado porque está faltando VCRUNTIME140.dll no seu computador. Tente reinstalá-lo para resolver esse problema." Ao fechar a mensagem, aparece outra dizendo "O programa não pode ser iniciado porque está faltando MSVCP140.dll no seu computador. Tente reinstalá-lo para resolver o problema." Eu baixei esses arquivos e colei na mesma pasta do Runner. Além disso, instalei o pacote  pacote 2017 C++ redistribuível atualizado e compatível com o sistema do PC (https://support.microsoft.com/pt-br/help/2977003/the-latest-supported-visual-c-downloads) e reiniciei o computador. Porém, ao tentar abrir o programa, aparece a mensagem "O aplicativo não pôde ser inicializado corretamente (0xc000007b). Clique em OK para fechar o aplicativo." 

Queria saber se o experimento feito no novo runner pode ter bugs devido ser rodado no runner antigo (o da Thais)?

**Comment by cpicanco** [comment]
As dlls de versão 140 correspondem ao pacote redistribuível c++ do visual
studio 2015. Tente instalar os pacotes correspondentes. Eles podem ser
baixados do site da Microsoft. Vc deve instalar o pacote correspondente a
arquitetura de sua máquina.

**Comment by cpicanco** [comment]
Sobre a sua pergunta, tecnicamente não são bugs. Versões anteriores
simplesmente não suportam funcionalidades que só existem em versões mais
recentes.

On Feb 20, 2018 17:11, "Rafael Picanço" <cpicanco42@gmail.com> wrote:

As dlls de versão 140 correspondem ao pacote redistribuível c++ do visual
studio 2015. Tente instalar os pacotes correspondentes. Eles podem ser
baixados do site da Microsoft. Vc deve instalar o pacote correspondente a
arquitetura de sua máquina.

**Comment by VALDERLON** [comment]
@cpicanco já fiz exatamente tudo que solicitaste com relação a instação do runner. Instalei a versão mais atualizada e compátível com as máquinas em que testei o software e mesmo assim o erro persiste. Não consigo abrir o programa e aprece a mensagem "O aplicativo não pôde ser inicializado corretamente (0xc000007b). Clique em OK para fechar o aplicativo."

Entendo que não são bugs, são problemas de incompatibilidade. Me expressei erroneamente. 

Creio que assim que consigamos resolver essa questão do novo runner, a maioria dos problemas será sanada.

**Comment by VALDERLON** [comment]
@cpicanco 
- Criei 3 pastas de participantes com as respectivas extensões 
![capturar](https://user-images.githubusercontent.com/22918273/36484713-efeee54c-16f8-11e8-87f9-04edb5684752.PNG)

-Consegui abrir o novo Runner com as configurações do meu experimento.
![capturar png2](https://user-images.githubusercontent.com/22918273/36484775-1a45dae4-16f9-11e8-8636-249770ddb500.PNG)

Contudo, não consigo adicionar os participantes. Quando abro a pasta do participante e ponho pra entrar como jogador, nada acontece. Não aparece aquela opção de escolher o nome do participante e aguardar o início do jogo.

**Comment by tidetomaz** [comment]
Estou enfrentando a mesma dificuldade que o Yan. Consigo abrir o runner como experimentador e o dos jogadores, entretanto não aparece para adiciona-los ao experimento e iniciar.

**Comment by cpicanco** [comment]
Muito bem. Bom saber que as coisas estão funcionando. Assim que for
possível envio uma nova versão. Thais me lembrou sobre esse problema com os
participantes. Vou corrigir isso mais tardar até semana que vem.

On Feb 21, 2018 12:52, "tidetomaz" <notifications@github.com> wrote:

Estou enfrentando a mesma dificuldade que o Yan. Consigo abrir o runner
como experimentador e o dos jogadores, entretanto não aparece para
adiciona-los ao experimento e iniciar.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lacs-ufpa/free-mtrix/issues/20#issuecomment-367371645>,
or mute the thread

**Comment by cpicanco** [comment]
@VALDERLON @tidetomaz , por favor, anexem o arquivo de sessão de vocês (o arquivo txt) aqui.

**Comment by VALDERLON** [comment]
[Teste LB Mag Atr Autocontrole.txt](https://github.com/lacs-ufpa/free-mtrix/files/1747921/Teste.LB.Mag.Atr.Autocontrole.txt)

**Comment by tidetomaz** [comment]
[Teste ACCultural Cpto Verbal - Tide.txt.txt](https://github.com/lacs-ufpa/free-mtrix/files/1748464/Teste.ACCultural.Cpto.Verbal.-.Tide.txt.txt)

**Comment by tidetomaz** [comment]
[Teste ACCultural Cpto Verbal - Tide..txt](https://github.com/lacs-ufpa/free-mtrix/files/1748468/Teste.ACCultural.Cpto.Verbal.-.Tide.txt)
