### ISSUE TITLE
(PRIORIDADE) Configuração de atraso nos contadores de Consequências culturais: 

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#21]
Como foi discutido antes, precisamos configurar o atraso para cada culturante, ou seja, cada culturante pode ter variação de atraso e essa variação deve poder ser modificada a depender da condição experimental (e.g. condição A: atraso de 10 dias para consequência do culturante autocontrolado; e condição B atraso de 20 dias para consequência do culturante autocontrolado).

**Comment by cpicanco** [comment]
Sim, trataremos disso no ticket sobre os contadores.
