### ISSUE TITLE
(PRIORIDADE MODERADA) Aumentar tamanho das figuras

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#23]
Como foi sugerido por alguns professores (Emmanuel e Aécio), gostaríamos que a distribuição das figuras (matriz e contadores) preencham o maio espaço possível na tela, afim de favorecer o controle de estímulos. Segue figura como sugestão. 
![slide1](https://user-images.githubusercontent.com/22918273/37349759-e0864592-26b5-11e8-9369-cf5a9bbefe5f.JPG)

**Comment by cpicanco** [comment]
Não será possível no momento, pois depende de algumas mudanças não previstas.
