### ISSUE TITLE
Tamanho das mensagens

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#24]
Assim como o tamanho maior das figuras pode favorecer o controle de estímulos, a mesma lógica se aplica às mensagens de produção de consequências individuais e culturais. Por isso, gostaríamos que as mensagens também apareçam maiores. Seguem figuras como sugestão.

![slide2](https://user-images.githubusercontent.com/22918273/37349827-11cd3214-26b6-11e8-9c9c-c064a4cb461f.JPG)
![slide3](https://user-images.githubusercontent.com/22918273/37349828-11f7b228-26b6-11e8-8426-9c36c70aee41.JPG)

**Comment by cpicanco** [comment]
Não será possível no momento, pois isso envolve mudanças não planejadas.
