### ISSUE TITLE
Tempo de apresentação da mensagem da Consequência Cultural:

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#25]
As mensagens das consequências culturais aparecem por 3s, mesmo tempo da mensagem das consequências individuais. Porém, como a quantidade de texto da mensagem da Consequência Cultural é maior (e.g., Vocês produziram 10 ITENS escolares que serão doados DAQUI A 10 DIAS a uma creche pública de Belém.), seria ideal ela ficar exposta durante 5 segundos.
(PRIORIDADE MODERADA)

**Comment by cpicanco** [comment]
No momento isso não será possível.

Do ponto de vista do programa, no presente momento existem três tipos de mensagens. Mensagens do sistema (que devem durar 5-s), Mensagens singulares (3-s) e Mensagens múltiplas (2.2-s para cada mensagem, o experimento da Thais tem esse tipo de mensagem).

Mensagens para o grupo ou para o indivíduo possuem a mesma duração, pois são mensagens singulares (3-s). Você tem duas opções, ou mantém como está ou ou amenta para ambos.
