### ISSUE TITLE
Adicionar sons (bipes)

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#26]
Adicionar sinais sonoros (bips) como reforçador condicionado tanto a resposta operante correta quanto culturante a cada ciclo. (EM LONGO PRAZO)

**Comment by cpicanco** [comment]
O que você está chamando de "resposta operante correta" e "culturante"? Descreva em relação aos aspecto do programa.

**Comment by cpicanco** [comment]
Olá Yan, você pode escolher um som e definir precisamente quando o ele deve ser apresentado? Por exemplo, após clicar no botão de confirmação? Após clicar sobre uma linha? Simultaneamente com a apresentação de uma mensagem? E assim por diante...

**Comment by VALDERLON** [comment]
Oi Rafael, 
O Damon testou parear (manualmente) sons contingentes apenas à produção de consequências culturais e isso surtiu o efeito esperado. Acho que sons apenas às consequências culturais é suficiente.

No meu caso, só precisaria de um som para consequências culturais impulsivas e outro som para as autocontroladas.  Ou seja, toda vez que uma das consequências for produzida, o son deve aparecer junto com a mensagem e com a soma de itens no contador. 

Eu vou enviar em breve os sons que o Damon utilizou. 

Obrigado

**Comment by VALDERLON** [comment]
Caro Rafael, 

encaminho as opções de sons para adicionar ao software caso seja viável. 

SOM PARA OS CULTURANTES IMPULSIVOS
https://www.dropbox.com/s/tcet6fkmr4ty5zw/01%20Blue%20Button.mp3?dl=0

SOM PARA OS CULTURANTES AUTOCONTROLADOS
https://www.dropbox.com/s/yn3kxingr4x1xqu/03%20Yellow%20Button.mp3?dl=0

Mais uma vez, reitero que esses sons devem ser contíguos à mudança de quantidade de itens nos contadores sempre que houver um dos entrelaçamentos programados. E que essa alteração não é tão urgente quanto a questão de zerar os contadores sempre que mudar uma condição.  

No mais, fico no aguardo de suas alterações casso sejam viáveis no momento.  

Att
