### ISSUE TITLE
Adicionar opção de repetir (replicar, copiar) uma condição

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#27]
Adicionar opção de repetir (replicar, copiar) uma condição sem ter que refazer as contingências operantes e culturantes (e.g., pra facilitar um experimento ABCABC).(EM LONGO PRAZO)

**Comment by cpicanco** [comment]
Não possível copiar uma condição explicitamente por meio do designer. Você, entretanto, pode editar diretamente o arquivo de configuração, copiando e colando livremente, mas mantendo o formato exigido pelo programa.
