### ISSUE TITLE
Randomização Participantes. 

### ISSUE THREAD

**Issue by tidetomaz** [lacs-ufpa/free-mtrix#29]
Rafael, em um dos testes no software, percebemos que o mesmo não estava randomizando a ordem dos participantes escolherem as linhas da matriz. Há algum tutorial de como configurar a randomização de escolhas dos participantes durante os ciclos?

**Comment by cpicanco** [comment]
A opção existe, no arquivo de configuração chama-se "Rodada.OrdemDeJogadaAleatória=1".

**Comment by tidetomaz** [comment]
Adicionei essa linha sugerida no arquivo, abaixo da linha com números de jogadores e agora o software está rodando de modo randomizado. Obrigado.
