### ISSUE TITLE
A seleção do campo “Apresentar pergunta ao final do ciclo” não permanece

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/free-mtrix#3]
A seleção do campo “Apresentar pergunta ao final do ciclo” não permanece de modo simultâneo quando há necessidade de replicação da condição no Experimento.

**Comment by cpicanco** [comment]
Não permanece ao realizar quê operação? Abrir e fechar? Mudar de condição?

**Comment by thaismguimaraes** [comment]
Não permanecia quando retornava para a primeira condição que havia selecionado o campo “Apresentar pergunta ao final do ciclo”, permanecendo na última condição que havia modificação.

**Comment by cpicanco** [comment]
Confirmado. Já já concerto isso.
