### ISSUE TITLE
Produção de consequências culturais em combinações de cores não programadas.

### ISSUE THREAD

**Issue by tidetomaz** [lacs-ufpa/free-mtrix#30]
Rafael, fizemos mais testes nos software e encontramos mais alguns problemas. Tentamos esgotar todas os possíveis erros decorrentes de configurações no designer ou no arquivo de texto. Ainda assim, algumas falhas na hora de rodar o programa.

Em nossos experimento, os Culturantes impulsivos serão compostos pelas combinações: VERDE + AMARELO + VERMELHO;  VERDE + AMARELO + AZUL;  ou VERDE + AMARELO + ROXO; e os Culturantes autocontrolados são AZUL + VERMELHO + VERDE; AZUL + VERMELHO + AMARELO; ou AZUL + VERMELHO + ROXO.

O Culturante impulsivo deve produzir, por exemplo: 1 item pra ser doado em 1 dia após o experimento. Enquanto que o autocontrolado deve produzir, por exemplo: 4 itens pra serem doados a partir de 30 dias. Tudo a depender da configuração.

Quando programados os 3 impulsivos e os 3 autocontrolados, eles produzem a quantidade correta de itens nos seus respectivos atrasos programados. Porém, combinações de cores não programadas também estão produzindo consequências e adicionando nos dois contadores ao mesmo tempo. Por exemplo, na combinação Vermelho + Vermelho + Verde, combinação para a qual nada está programado, hora ele produz uma consequência impulsiva, outra hora produz uma autocontrolada, sendo ambas adicionadas aos dois contadores. Segue a imagem abaixo como exemplo. Isso acontece em outras combinações não programadas (e.g., VERMELHO + VERMELHO + VERDE). 

![bug-freemtrix](https://user-images.githubusercontent.com/36206541/37928617-bd188f4e-3113-11e8-8a49-74aa603e2224.jpg)

Acreditamos que esteja ocorrendo algum problema no runner ou designer, pois quando ocorresse alguma escolha de cores não programada (e.g. roxo + roxo + amarelo), nada deveria ocorrer. Ou seja, o próximo ciclo iniciaria sem que nenhuma consequência cultural aparecesse nos contadores. 

 Nos colocamos à disposição para eventuais necessidades para mais informações.

**Comment by cpicanco** [comment]
Olá @tidetomaz. Não identifiquei nenhum lógico entre o que foi implementado e o que foi solicitado por @VALDERLON 

## O que ele pediu?

> No meu caso, e do Tide, um culturante precisaria ser especificado na combinação verde+amarelo+qualquer outra cor, e outro culturante na azul+vermelho+qualquer outra cor.

Isto foi foi feito por meio `conjuntos`. Se o conjunto de cores escolhido pelos participantes está contido no conjunto definido pelo experimentador, então a consequência deve ocorrer.

Para mim não ficou claro qual a lógica que você deseja. Você pode confirmar para mim se o que você deseja é diferente do que foi solicitado pelo Yan? Se sim, por favor, descreva o mais precisamente e o mais sucintamente possível o que você deseja.

**Comment by cpicanco** [comment]
@tidetomaz , 

Supondo que eu esteja entendendo o que você quer, o programa já permite fazer o que foi relatado por você:

> Em nossos experimento, os Culturantes impulsivos serão compostos pelas combinações: VERDE + AMARELO + VERMELHO; VERDE + AMARELO + AZUL; ou VERDE + AMARELO + ROXO; e os Culturantes autocontrolados são AZUL + VERMELHO + VERDE; AZUL + VERMELHO + AMARELO; ou AZUL + VERMELHO + ROXO.

Basta criar 6 culturantes, um para cada combinação de cores específicas, por exemplo:

Culturantes do tipo 1
VERDE + AMARELO + VERMELHO;
VERDE + AMARELO + AZUL;
VERDE + AMARELO + ROXO;

Culturantes do tipo 2
AZUL + VERMELHO + VERDE;
AZUL + VERMELHO + AMARELO;
AZUL + VERMELHO + ROXO.

**Comment by VALDERLON** [comment]
Então @cpicanco 
quando expliquei minhas contingências pra você, eu tinha colocar nesses termos: VERDE + AMARELO + QUALQUER OUTRA COR (impulsivos) e AZUL + VERMELHO + QUALQUER OUTRA COR (autocontrolados). Mas quando fui configurar os experimentos, percebi que isso que eu descrevi, na verdade são 2 grupos de 3 culturantes (os tipo 1 e 2 que você citou acima). 

Por isso, na configuração dos experimentos, fizemos exatamente assim, configuramos essas 6 combinações, os 3 culturantes impulsovos e os 3 autocontrolados, e suas respectivas consequências e mensagens. 

O foco da nossa questão é: em combinações de cores não programadas, o programa adiciona consequências e mostra mensagens. Por isso, acreditamos que esteja ocorrendo algum problema no runner ou designer. 

Pra você constatar o que estamos dizendo, faça um teste com a nossa configuração (arquivo .ini compilado abaixo). As consequências e mensagens dos 6 culturantes programados estão corretas. Mas quando acontece qualquer combinação não programada (e.g., azul + azul + amarelo), ao invés não acontecer nada e iniciar o próximo ciclo, o programa apresenta mensagem e adiciona consequências culturais aos dois contadores.

[Experimento]
Pesquisador.Nome=João Aristides Tomaz de Almeida
Nome=Autocontrole Cultural e Comportamento Verbal
Objetivo=Avaliar os efeitos da interação verbal na seleção de culturantes autocontrolados.
Jogadores.Novos.Enviar_Histórico_do_BatePapo=0
Jogadores.GerarAutomaticamente=0
Pesquisador.PodeJogar=0
Pesquisador.BatePapo=0
Jogadores.BatePapo=0
TipoDePontuação=0
TipoDaMatrix=CORES,LINHAS,

[Condição.1]
Culturante1.Contador.Rótulo=Itens escolares que serão doados\n daqui à 1 dia.
Culturante2.Contador.Rótulo=Itens escolares que serão doados\n daqui à 30 dias.
Nome=A - Interação Verbal Permitida
Rodada.NúmeroDeJogadores=3
Pontos.Somar_ao_iniciar_condição.A=0
Pontos.Somar_ao_iniciar_condição.B=0
Pontos.Somar_ao_iniciar_condição.I=0
Pontos.Somar_ao_iniciar_condição.G1=0
Pontos.Somar_ao_iniciar_condição.G2=0
Ciclos.MudançaDeGeração=100
Critério_de_Finalização.Estilo=O QUE OCORRER PRIMEIRO
Critério_de_Finalização.Ciclos=100
Critério_de_Finalização.Porcentagem=80,50
.Resposta=|CORES|AMARELO,VERDE,AZUL,ESPECIFICAMENTE,|
.Consequência.Mensagem.Prefixo=Vocês doaram 1 item escolar a uma escola pública.
.Consequência.Mensagem.Prefixo_ao_perder=
.Consequência.Mensagem.Sufixo_ao_perder.Singular=
.Consequência.Mensagem.Sufixo_ao_perder.Plural=
.Consequência.Mensagem.Prefixo_ao_ganhar=
.Consequência.Mensagem.Sufixo_ao_ganhar.Singular=
.Consequência.Mensagem.Sufixo_ao_ganhar.Plural=
.Consequência.Mensagem.Sufixo_zero=

Contingência.1.Nome=Operante Impar
Contingência.1.Resposta=IMPAR,|LINHAS||
Contingência.1.Consequência=2,0|M,C,P,I,
Contingência.1.Consequência.Mensagem.Prefixo=$NICNAME ganhou 2 fichas.

Contingência.2.Nome=Operante Par
Contingência.2.Resposta=PAR,|LINHAS||
Contingência.2.Consequência=1,0|M,C,P,I,
Contingência.2.Consequência.Mensagem.Prefixo=$NICNAME ganhou 1 ficha.
.Consequência=1,0|M,P,G1,

Metacontingência.1.Nome=Cult Impulsivo 1
Metacontingência.1.Resposta=|CORES|AMARELO,VERDE,AZUL,ESPECIFICAMENTE,|
Metacontingência.1.Consequência=1,0|M,P,G1,
Metacontingência.1.Consequência.Mensagem.Prefixo=Vocês produziram 1 item escolar que será doado a uma creche de Belém.

Metacontingência.2.Nome=Cult Impulsivo 2
Metacontingência.2.Resposta=|CORES|AMARELO,VERDE,ROXO,ESPECIFICAMENTE,|
Metacontingência.2.Consequência=1,0|M,P,G1,
Metacontingência.2.Consequência.Mensagem.Prefixo=Vocês produziram 1 item escolar que será doado a uma creche de Belém.

Metacontingência.3.Nome=Cult Impulsivo 3
Metacontingência.3.Resposta=|CORES|AMARELO,VERMELHO,VERDE,ESPECIFICAMENTE,|
Metacontingência.3.Consequência=1,0|M,P,G1,
Metacontingência.3.Consequência.Mensagem.Prefixo=Vocês produziram 1 item escolar que será doado a uma creche de Belém.

Metacontingência.4.Nome=Cult Autocontrolado 1
Metacontingência.4.Resposta=|CORES|VERMELHO,AZUL,ROXO,ESPECIFICAMENTE,|
Metacontingência.4.Consequência=4,0|M,P,G2,
Metacontingência.4.Consequência.Mensagem.Prefixo=Vocês produziram 4 itens escolares que serão doados a uma creche de Belém.

Metacontingência.5.Nome=Cult Autocontrolado 2
Metacontingência.5.Resposta=|CORES|VERMELHO,VERDE,AZUL,ESPECIFICAMENTE,|
Metacontingência.5.Consequência=4,0|M,P,G2,
Metacontingência.5.Consequência.Mensagem.Prefixo=Vocês produziram 4 itens escolares que serão doados a uma creche de Belém.

Metacontingência.6.Nome=Cult Autocontrolado 3
Metacontingência.6.Resposta=|CORES|AMARELO,VERMELHO,AZUL,ESPECIFICAMENTE,|
Metacontingência.6.Consequência=4,0|M,P,G2,
Metacontingência.6.Consequência.Mensagem.Prefixo=Vocês produziram 4 itens escolares que serão doados a uma creche de Belém.
Questão.Mensagem=
Questão.Estilo=

No mais, continuamos à disposição e aguardamos suas considerações.

**Comment by cpicanco** [comment]
Há uma nova versão em anexo. De fato havia um erro lógico ao comparar as cores escolhidas com as cores selecionadas como critério.
[experiment_runner_windows_32bits_v0.2.0.14-17-g88a39bc.zip](https://github.com/lacs-ufpa/free-mtrix/files/1868943/experiment_runner_windows_32bits_v0.2.0.14-17-g88a39bc.zip)

**Comment by tidetomaz** [comment]
@cpicanco baixamos a versão que você enviou do runner, fizemos testes preliminares e aparentemente o problema de produção de consequências não programadas foi resolvido. Amanhã continuaremos testando todas as combinações de escolhas de cores possíveis a fim de verificar se estará tudo ok. Agradecemos de antemão pela atenção e suporte.
