### ISSUE TITLE
ATRIBUIÇÃO DE CRITÉRIO DE MUDANÇA DE CONDIÇÃO AOS 2 GRUPOS DE CULTURANTES

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#31]
Rafael, 

Encontramos mais um contratempo que foi devido a falta de clareza de nossa parte em relação às especificidades de nosso delineamento. 

O que acontece é que a contabilização dos acertos e, consequentemente, cálculo da probabilidade pelo software está sob função de apenas um dos 6 entrelaçamentos programados. No caso, apenas na combinação VERDE + AMARELO + AZUL é que o critério está sendo calculado. (ver figura)

![criterio](https://user-images.githubusercontent.com/22918273/38274647-c1b20b04-3765-11e8-91ad-f7d9f3ee39e8.png)

Na figura é possível ver que houveram 4 entrelaçamentos, sendo que esses 4 foram nas combinações dos culturantes impulsivos. O primeiro entrelaçamento composto por VERDE + AMARELO + ROXO, o segundo entrelaçamento composto por VERDE + AMARELO + ROXO, o tericeio entrelaçamento composto por VERDE + AMARELO + VERMELHO, e o quarto entrelaçamento composto por VERDE + AMARELO + AZUL. Constatamos que apenas este último foi contabilizado pelo software como culturante-alvo. 

Em relação aos culturantes autocontrolados (AZUL + VERMELHO + VERDE; AZUL + VERMELHO + AMARELO; ou AZUL + VERMELHO + ROXO), nenhum deles foi contabilizado pelo software  para o cálculo de critério de mudança de condição. Em outro teste, fizemos apenas combinações dos culturantes autocontrolados e a porcentagem permaneceu 0% (zero porcento).

Só agora percebemos que o critério deve ser atribuído semparadamente aos dois grupos de culturantes. De modo que devem ser contabilizados todos os culturantes impulsivos e todos os autocontrolados separadamente e divido o valor dessa soma pela quantidade de ciclos. 

Por exemplo, numa condição com 100 ciclos, caso ocorram 20 combinações VERDE + AMARELO + ROXO e 20 combinações VERDE + AMARELO + VERMELHO, e também 20 combinações AZUL + VERMELHO + ROXO e 20 combinações AZUL + VERMELHO + VERDE o cálculo deve ser feito somando os impulsivos (40 ocorrências de culturantes impulsivos) divido pela quantidade de ciclhos, o que daria 40/100=40% de impulsivos; e o mesmo com os autocontrolados, o que daria também 40% de autocontrolados. 

Acho que o programa foi feito pensando em APENAS UM culturante-alvo, por isso tivemos esse problema. Mas precisamos que o critério seja atrbuído para OS 2 GRUPOS DE CULTURANTES, os 3 impulsivos e os 3 autocontrolados, separadamente.

No mais, continuamos à disposição para maiores esclarecimentos.

**Comment by cpicanco** [comment]
Olá @VALDERLON , essa alteração poderá tardar a ser implementada. Recomendo avaliar a possibilidade de usar exclusivamente o critério fixo baseado no número de ciclos.

**Comment by cpicanco** [comment]
Olá @VALDERLON , qual a situação dessa solicitação?

**Comment by VALDERLON** [comment]
Oi Rafael,

optamos por deixar fixo 100 ciclos em todas as condições para facilitar comparações entre grupos. Portanto, não há necessidade de fazer essa alteração no momento. Talvez não precise mais dessa alteração, mas só poderemos saber depois das próximas coletas.

**Comment by cpicanco** [comment]
Show

Rafael
