### ISSUE TITLE
Redução de linhas da figura da tarefa

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/free-mtrix#32]
Reduzir a figura da tarefa de 10 linhas numeradas de 1 a 10 para quatro linhas numeradas de 1 a 4, cada uma com cor diferente.

**Comment by cpicanco** [comment]
Olá Thais, há uma nova versão do runner está em anexo, por favor, teste-a.

[experiment_runner_windows_32bits_v0.2.0.14-18-g5be6a51.zip](https://github.com/lacs-ufpa/free-mtrix/files/1885828/experiment_runner_windows_32bits_v0.2.0.14-18-g5be6a51.zip)

O Designer pode ser encontrado aqui:

https://github.com/lacs-ufpa/free-mtrix/releases

**Comment by thaismguimaraes** [comment]
Obrigada :)

**Comment by cpicanco** [comment]
Thais, a lógica do experimento do @VALDERLON  não servirá para o seu. Amanhã finalizamos isso.
