### ISSUE TITLE
CONTABILIZAÇÃO DE ITENS ESCOLARES AO FINAL DO EXPERIMENTO. 

### ISSUE THREAD

**Issue by tidetomaz** [lacs-ufpa/free-mtrix#34]
Olá Rafael, hoje num dos últimos testes do softaware, vimos que a mensagem ao final do experimento que é apresentada aos participantes está contabilizando apenas 1 combinação de cores (VERDE + AMARELO + AZUL) dentre as 6 combinações programadas. Como você pode ver na imagens em anexo os participantes hipoteticamente haviam produzido 42 itens ao total, porém o software só reconhece 10 itens. Há algum reparo nessa configuração que seja possível? Ou segue a mesma lógica de a capacidade atual do software, que é de contabilizar apenas 1 das 6 combinações programadas? 

![culturantes](https://user-images.githubusercontent.com/36206541/38760183-80d37184-3f69-11e8-85ac-81d0bfc2281f.jpg)

![experimento final](https://user-images.githubusercontent.com/36206541/38760195-8a39a734-3f69-11e8-831b-293211a922ec.jpg)

**Comment by cpicanco** [comment]
Olá @tidetomaz , há uma nova versão em anexo.

[experiment_runner_windows_32bits_v0.2.0.14-21-g6e7cf1d.zip](https://github.com/lacs-ufpa/free-mtrix/files/1909947/experiment_runner_windows_32bits_v0.2.0.14-21-g6e7cf1d.zip)
