### ISSUE TITLE
ZERAR O CONTADOR AO FINAL DE CADA CONDIÇÃO

### ISSUE THREAD

**Issue by VALDERLON** [lacs-ufpa/free-mtrix#35]
@cpicanco 

ontem rodei minha primeira microcultura e, na condição em que havia variação apenas do atraso (dias em que os item serão doados), o grupo manteve o padrão da condição anterior. Ou seja, os dois grupos de culturantes produzia a mesma quantidade de itens, só que um imediato e outro atrasado. A hipótese é de que nesta condição, eles produziriam o mais imediato. Porém, mesmo eles   tendo percebido a diferença apenas do atraso, eles se mantiveram no culturante que havia sido selcionado na condição anterior com o objetivo de "voltar a produzir mais itens mais imediatos".

Eles fizeram isso, porque o contador acumulou os itens da condição anterior (em que variava apenas a quantidade de itens) e acharam que se eles se mantivessem no mesmo culturante o atraso ia voltar para mais imediato com mais itens. 

Creio que se zerar o contador de culturantes ao final de cada ciclo, ajude a controlar isso. Sendo deve zerar apenas pra eles, mas deve continuar a soma de todos os itens produzidos ao final do experimento. 

Ainda vou rodar mais uma microcultura do jeito que está, só pra garantir.

Se for possível fazer alteração apenas no runner, não tem problema, basta me dizer qual o comando colocar no arquivo de texto. 

Fico à disposição para esclarecimentos.

**Comment by cpicanco** [comment]
Você quis dizer zerar os contadores ao final de cada condição, correto?Acho
que é possível dizer que cada condição deve possuir seu próprio conjunto de
contadores, independentes de outras condições (à rigor, o contador não
zera, ele muda). Se for isso, faz sentido mudar o contador apenas quando o
culturante mudar.

Eu não confiaria apenas na mudança do contador. Eu sugiro que você faça
algo parecido com o que o Tide fez. Deve ficar claro para eles que as
mudanças nas condições independem do comportamento deles.

Infelizmente, não terei disponibilidade de fazer isso no momento. Estarei
disponível a partir do final de maio, após o concurso.

**Comment by VALDERLON** [comment]
Tu diz de fazer a projeção na televisão avisando da mudança de condições, correto?

É uma alternativa viável até a alteração ser possível. 

Obrigado

**Comment by VALDERLON** [comment]
Olá @cpicanco,

gostaria saber se, no momento, seria viável fazer a modificação sugerida nessa "issue"? 

Tenho planos de coletar em meados de Novembro. Caso seja possível, agradeço. Caso não seja possível, poderias me dar uma estimativa pra eu poder programar as futuras coletas? 

Abraço.

**Comment by cpicanco** [comment]
Olá @VALDERLON , 

Perdão, mas de fato não está claro qual a alteração sugerida.

**Comment by cpicanco** [comment]
Olá Yan,

O que você acha de apresentar uma mensagem em tela cheia no início de cada
condição, algo como "O sistema complexo de ponderação mudou"?

Rafael

**Comment by VALDERLON** [comment]
Rafael, 

Tua sugestão é eu por uma mensagem destacando a mudança condição sem zerar o contador?

Não se isso causaria o efeito de "controle de estímulos" necessário para eles atentarem para a variação nas consequências culturais.

Salvo engano, tu tinha sugerido, também, algo como eu pausar o experimento e reiniciar em cada condição, mas isso o Emmanuel disse que não é interessante assim, porque sinalizar a mudança de condição pode gerar variação de cultuarantes (o pessoal começar a variar pra ver o que acontece). Ou seja, isso pode ser uma Variável Estranha.  

O ideal é que eles fiquem sob controle das consequências produzidas e não de instruções. 

Por isso, temo que seja necessário insistir nessa alteração de zerar os contadores de consequências culturais. 

Me avise se for possível fazer a alteração e se há um prazo pra isso pra eu poder me organizar para as coletas futuras. 

Abraço!

**Comment by cpicanco** [comment]
Zerar o contador sinaliza a mudança de uma condição e pode funcionar como
uma variável estranha também.

Rafael

**Comment by VALDERLON** [comment]
Concordo Rafael, mas creio que zerar o contador seja uma mudança menos evidente do que eu ter que parar o experimento e reiniciar em cada condição e, ainda, uma mudança que controlaria mais a emissão dos culturantes-alvo do que apenas uma aviso (sem zerar o contador).

De todo modo, isso implica que você não poderá fazer a alteração solicitada?

**Comment by cpicanco** [comment]
Alterações demandam tempo, esforço e dedicação. Estou tentando compreender
a necessidade da alteração sugerida por você.

Uma mudança "menos evidente", isto é, com menos chances de controlar o
comportamento dos participantes, não me parece ser necessária. Afinal, você
espera justamente que a mudança exerça controle sobre o comportamento.

Fico à disposição para outras questões.

Abraço,
Rafael

**Comment by VALDERLON** [comment]
Entendo suas preocupações Rafael. 

Acho que "mudança menos evidente" não foi minha melhor descrição do problema. Minha maior preocupação é controlar as variáveis estranhas. Veja, por exemplo, o que aconteceu no dado que mandei na mensagem anterior: aparentemente, uma vez selecionado o culturante que produzia a consequência de maior magnitude, o atraso parece não ter relevância nenhuma. Um dos participantes chegou a comentar assim "vamos continuar nessa combinação, que uma hora a gente volta a ganhar 12 itens em um dia", isso durante a condição B. Isso me leva a crer que eles agiram assim, porque o contador não zerava.

Concordo que zerar o contador pode sinalizar mudança de condição, contudo, ainda assim, seria uma alteração necessária, haja vista o seguinte:

    1. Se eu optar por colocar uma mensagem sinalizando a variação de atraso e/ou de magnitude, pode ser que eles hajam, em parte, em função de uma instrução externa ao invés de agirem em função exclusiva das consequências culturais. Mesmo que eles mesmo digam entre si como “alguma coisa mudou” ou “esse contador não estava assim”, ainda assim, o que controlaria a recorrência do culturante, seriam as consequências culturais e não a instrução externa.
   
   2. Se eu optar por reiniciar o experimento em cada condição, mesmo que não haja nenhuma instrução, pode ser que os participantes comecem a fazer coisas diferentes para “ver o que foi que mudou” ao invés de, novamente, ficarem sobre controle das consequências culturais produzidas. Isso era muito comum nos experimento antigos que tinham muitos distratores (e.g., bolinhas preenchidas e vazadas), ou seja, coisas que não tinham nenhuma relação com as manipulações fizeram com que os participantes dispersassem e perdessem tempo variando combinações pra descobrir “pra que serve isso” entende?

Ainda estou vendo com o Emmanuel e com pessoal do laboratório outras opções para controlar as variáveis estranhas como: a) modificar os valores das magnitudes das CCs e dos atrasos de modo a haver uma gradação linear entre quantidade de itens e atrasos (e.g., 1 item em 1 dia versus 12 itens em 12 dias); b) programar apenas um culturante impulsivo e um autocontrolado em cada condição, porque, no momento, são grupos de 3 impulsivos e 3 autocontrolados para cada condição. Nesse sentido, zerar os contadores ajudaria a controlar esse efeito (já visto no piloto) de “tentar voltar pro atraso da condição anterior”.

No mais, veja minhas justificativas e avalie o que é possível ser feito. 
abraço

**Comment by cpicanco** [comment]
Olá Yan,

Você já pensou sobre remover o contador? Dessa forma você evita qualquer tipo de controle pelo contador e ao mesmo tempo não cria nenhuma "dica" entre as condições.

Fico no aguardo sobre sua decisão,

Abraço
Rafael

**Comment by VALDERLON** [comment]
Rafael, 

remover o contador descaracterizaria e experimento, haja vista que minhas manipulações envolvem, justamente, variação de atraso e magnitude das consequências culturais. Essa variação é sinalizada pelos contadores. Não vejo como executar meu experimento sem os contadores. 

Novamente, aguardo suas considerações. 

Abraço

**Comment by cpicanco** [comment]
Olá Yan, você pode incluir o atraso diretamente na mensagem do culturante.
Mas creio que dessa forma a contagem e eventual comparação entre os
acumulados se tornem mais difíceis.

Rafael

**Comment by VALDERLON** [comment]
Rafael, 

a variação de atraso e magnitude já aparece nas mensagens ao final de cada ciclo. Inclusive, salvo engano, você que sugeriu isso e adicionou a opção de mensagem para cultuantes ainda na época das primeiras versões. Zerar os contadores seria uma alteração adicional à mensagem. 

Abraço

**Comment by cpicanco** [comment]
Bem, infelizmente não será possível entregar essa alteração ainda em novembro, pois não é trivial o trabalho de David e Laís são prioritários. Qual o seu prazo para a coleta de dados?

**Comment by VALDERLON** [comment]
Oi Rafael,

há previsão para fazer estas alterações no programa para as minhas coletas?

att

**Comment by cpicanco** [comment]
Olá, Yan

Espero concluir as alterações para o experimento da Laís essa semana. Parte
do trabalho com contadores e condições será reaproveitado para o seu.

Abraço,
Rafael

**Comment by VALDERLON** [comment]
Tudo bem, 

ficarei aguardando suas modificações. 

Abraço
