### ISSUE TITLE
Alteração do texto na interface do software

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#36]
Boa tarde @cpicanco , gostaria de alterar as informações na interface do software, para ter ao menos um esboço de como ficaria o programa. Na figura abaixo, retirada do trabalho do Tide, gostaria de modificar as informações dos quadros, onde está "Fichas", "Itens escolares..." e lá em baixo "Escolhas na última jogada". Como faço isso? Obrigado!!

![interface](https://user-images.githubusercontent.com/36678200/40879550-28d570fa-6678-11e8-9368-e8e36c6c4381.png)

**Comment by cpicanco** [comment]
Olá @daviddelimarabelo , consulte essa discussão: https://github.com/lacs-ufpa/free-mtrix/issues/17, qualquer dúvida, por favor não exite, entre em contato novamente.
