### ISSUE TITLE
Condição de análogo de reforçamento negativo

### ISSUE THREAD

**Issue by damomribeiro** [lacs-ufpa/free-mtrix#37]
Olá Rafael. Para a condição de reforçamento negativo (B) do meu experimento, será preciso fazer algumas **alterações logo no início da condição.**

&#10148; A mensagem "A partir de agora os itens escolares serão subtraídos” deve aparecer logo no início das condições B.

&#10148; Também a partir do começo da condição B, deverá ocorrer a subtração de um item escolar a cada 30 segundos, não sinalizados aos participantes, independente de qualquer resposta dos participantes. 

&#10148; Alteração de cor do contador de itens escolares de preto para laranja durante a subtração de itens na condição B.

[Effects of Negative Reinforcement on Culturants Selection.txt](https://github.com/lacs-ufpa/free-mtrix/files/2189961/Effects.of.Negative.Reinforcement.on.Culturants.Selection.txt)

**Comment by cpicanco** [comment]
@damomribeiro , não é possível subtrair um item escolar do contador de forma não sinalizada. O contador é a sinalização. :smile: Você poderia deixar mais claro esse segundo ponto?

**Comment by damomribeiro** [comment]
@cpicanco o que não será sinalizado aos participantes é o tempo (30 segundos) entre uma subtração e outra. Ou seja, não haverá um timer aqui.

**Comment by cpicanco** [comment]
O que você acha melhor, apresentar a mensagem "A partir de agora os itens escolares serão subtraídos" em cada computador ou na TV?

**Comment by damomribeiro** [comment]
Existe a possibilidade de apresentar nos dois? Acho que seria bom garantir que todos vissem.

**Comment by cpicanco** [comment]
Beleza
