### ISSUE TITLE
Experimento do Damon

### ISSUE THREAD

**Issue by damomribeiro** [lacs-ufpa/free-mtrix#38]
Quanto ao timer que deverá está presente nas condições B.

&#10148; Aparecimento do timer quando houver ocorrência do cult 2, causando a suspensão da subtração de itens nas condições B

&#10148; Regressão do tempo marcado pelo timer de 30 até 0.

&#10148; Desaparecimento do timer após 30 segundos, caso não ocorra o Cult 2 novamente.

&#10148; Quando o timer desaparecer, volta-se a perder os itens como no começo da condição B.

&#10148; O timer deve ser resetado para 30 segundos sempre que ocorrer o cult 2.

Segue prévia de como planejamos a interface no projeto:
![interface 4 0](https://user-images.githubusercontent.com/39706036/42659120-a8cb8f48-85fd-11e8-91e5-2b693d1240c3.jpg)

**Comment by cpicanco** [comment]
@damomribeiro , como eu já havia conversado com você, sincronizar o tempo entre os computadores de uma rede não é um problema trivial.

Tenho uma sugestão alternativa. Eu tenho um cabo hdmi de 6 m (se eu não estiver enganado é esse o tanho, mas qualquer coisa você já vai procurando um cabo grande o suficiente). A ideia é ligar a TV no computador que funciona como servidor. Dessa forma, o computador apresentará o relógio diretamente na TV, sem necessidade de sincronizar o tempo. O servidor enviará para e receberá dos clientes (os computadores dos participantes) os eventos que forem necessários de forma assincrônica (dentro dos limites de latência da rede local), como já funciona.

**Comment by cpicanco** [comment]
@damomribeiro, por favor, me envie um fluxograma com as etapas do experimento.

**Comment by damomribeiro** [comment]
@cpicanco o ideal seria seguirmos o projeto original. No caso de não conseguirmos, acho que sua ideia pode funcionar, mas devo conferir com o Emmanuel se ele aprova as modificações.

Abaixo, o fluxograma com as etapas do experimento.
![fluxograma completo](https://user-images.githubusercontent.com/39706036/42901713-b5b82a3c-8aa2-11e8-848a-fdb18fbad196.jpg)

**Comment by cpicanco** [comment]
@damomribeiro , bem, aguardarei seu retorno então.

**Comment by damomribeiro** [comment]
@cpicanco na última reunião que tivemos com ele foi falado que tentaríamos fazer do modo como estava no projeto e, caso você não conseguisse contornar a dificuldade com a sincronização do tempo, nós faríamos alguns ajustes, mas isso sempre foi o plano B. Seria interessante se tentássemos seguir o projeto original primeiro. Seria o ideal.

**Comment by cpicanco** [comment]
olá Damon, a cara da tela da televisão por enquanto está assim:
![screenshot from 2018-08-06 21-39-39](https://user-images.githubusercontent.com/6511849/43747620-74e5a588-99c1-11e8-9eb2-bc918e6e229c.png)

Por favor, confirme para mim se está faltando algo ou não.

**Comment by damomribeiro** [comment]
Tá bem bacana. A gente queria que ficassem todos os contadores na televisão. E no computador dos participantes só a matrix.

**Comment by cpicanco** [comment]
Damon, o que deve acontecer se o contador de itens escolares zerar quando houver retirada de item a cada 30 segundos?

**Comment by cpicanco** [comment]
@damomribeiro (apenas marcando).

**Comment by damomribeiro** [comment]
Zerar o contador é critério para passar para próxima condição. E no caso da segunda condição B, critério para encerramento.

**Comment by damomribeiro** [comment]
A ideia inicial é que não. Todos os possíveis itens perdidos nas condições B deverão ser produzidos nas condições A que os precederão. No entanto, há uma possibilidade do orientandor exigir uma microcultura com delineamento BABA, nesse caso as condições B devem iniciar com uma quantia de itens (provavelmente 100).

**Comment by damomribeiro** [comment]
Acho que tá ótimo.

**Comment by cpicanco** [comment]
@damomribeiro , encontrei um problema ao tentar implementar o encerramento de sessão tendo como base o número de itens escolares. Contudo, a versão atual já permite você ir testando os outros aspectos do delineamento.

Você deve usar o seguinte arquivo de sessão:
[damon.txt](https://github.com/lacs-ufpa/free-mtrix/files/2287178/damon.txt)

Você deve usar a seguinte versão do programa:
[experiment_runner_windows_32bits_damon.zip](https://github.com/lacs-ufpa/free-mtrix/files/2287171/experiment_runner_windows_32bits_damon.zip)

Qualquer dúvida é só falar.

**Comment by damomribeiro** [comment]
@cpicanco fiz os testes todos utilizando quatro notebooks, um como servido e outros três para cada participante.

- A condição A rodou muito bem.

- Aqui nos meus testes a condição B travou após a a escolha do participante 2, impedindo também o participante 3 de fazer escolhas. Ocorreu no segundo ciclo de duas das vezes que testei. 
 
- Na condição B os itens não foram subtraídos quando o cronômetro chegou a zero mesmo quando ocorreu o culturante alvo.
 
- O cronômetro não reiniciou de modo contingente ao culturante. Ficou em loop infinito.

**Comment by cpicanco** [comment]
@damomribeiro ,

Minha compreensão da Fase B é a seguinte:

FASE B
- No início da condição B.
  - Iniciar contagem regressiva P de 30 segundos;
    - mudar a cor de itens escolares para laranja.
    - ao final da contagem, um item escolar deve ser retirado e a contagem regressiva P deve ser reiniciada (loop infinito).
    - A contagem não possui um temporizador visível na tela.
- Ao longo da condição B.
  - quando um culturante alvo ocorrer durante a contagem regressiva P
    - parar contagem regressiva P;
    - mudar a cor do contador de itens para preto;
    - mostrar um temporizador na tela;
    - iniciar contagem regressiva A;
       - se a contagem já estiver em curso reiniciar contagem de 30 segundos;
  - ao final da contagem regressiva A iniciar contagem regressiva P de 30 segundos;

A versão que eu enviei a você sempre mostra o temporizador, pois está em fase de testes.

**Comment by damomribeiro** [comment]
É isso mesmo, @cpicanco.

**Comment by cpicanco** [comment]
Olá Damon,

Por favor, teste a versão em anexo.

Recomendo aumentar o número de ciclos por sessão mudando o valor  da configuração `Critério_de_Finalização.Ciclos` para algo maior do que dois:
```
[Condição.1]
Nome=Condição A1
Rodada.NúmeroDeJogadores=3
Pontos.Somar_ao_iniciar_condição.A=0
Pontos.Somar_ao_iniciar_condição.B=0
Pontos.Somar_ao_iniciar_condição.I=0
Pontos.Somar_ao_iniciar_condição.G1=0
Pontos.Somar_ao_iniciar_condição.G2=0
Ciclos.MudançaDeGeração=410
Critério_de_Finalização.Estilo=CICLOS
Critério_de_Finalização.Ciclos=2
Critério_de_Finalização.Porcentagem=80,10
```
Recomendo usar dois monitores (ou um monitor e a tv) no modo Desktop Extendido. Arraste a janela contendo o cronômetro e contadores para o espaço do monitor secundário.
Baixe o programa aqui: [experiment_runner_windows_32bits.zip](https://github.com/lacs-ufpa/free-mtrix/files/2346992/experiment_runner_windows_32bits.zip)

**Comment by cpicanco** [comment]
@damomribeiro , lembrando que a condição "encerrar condição se contador de item atingir zero" ainda não existe.

**Comment by damomribeiro** [comment]
@cpicanco testei duas vezes nos mesmos notebooks que testei a primeira versão. Seguindo os mesmos passos da vez que rodou sem problemas. Porém, nessa versão não consigo acrescentar o segundo participante. Inclusive, tentei trocar a ordem dos notebooks, mas o problema persistiu. Apos a entrada do primeiro participante nenhum dos outros é reconhecido pelo servidor.

**Comment by cpicanco** [comment]
@damomribeiro , testei aqui e está funcionando. Recomendo que você delete todas as versões anteriores do programa e confira se o ip de cada participante está corretamento configurado com o ip do servidor.

**Comment by damomribeiro** [comment]
@cpicanco eu tinha configurado os arquivos IP e id. Executei tanto em modo administrador como no modo normal. Troquei a ordem em que os participantes entravam e mesmo assim não deu certo. Pedi até para o @VALDERLON dá uma olhada, mas mesmo assim continuou na mesma. Quando o segundo participante entra a sua entrada não é acusada no servidor. De qualquer modo, vou testar de novo.

**Comment by cpicanco** [comment]
@damomribeiro , 

Vamos lá, por partes:

1. Você não deve configurar o `id`. Esse arquivo é gerado automaticamente.
1. Para cada participante usando um computador diferente, você deve escrever o no arquivo `IP` o endereço IP do computador do servidor. Note-se, todos os computadores devem estar conectados na mesma rede local.
1. Não há necessidade de rodar o programa no modo administrador.
1. Não há necessidade de trocas a ordem dos participantes.
1. Você pode rodar tudos os participantes e o servidor em um mesmo computador. Nesse caso, NÃO CONFIGURE O IP, ele é automaticamente configurado.

Da próxima vez que você testar, por favor:
1. anote o endereço IP do servidor e me envie os arquivos `IP` de cada participante;
1. me envie o arquivo de configuração da sessão.

Abraço,
Rafael

**Comment by damomribeiro** [comment]
@cpicanco deu certo (o erro tinha sido o na etapa do arquivo id). Feito o texto pude perceber que:

- Ao passar da condição A para a B, a mensagem apareceu com um certo atraso e mais um ciclo da condição A pôde ser concluído., só então passou-se para a condição B. A mensagem deveria aparecer de modo que os participantes não pudessem mais fazer escolhas após seu aparecimento.

- Na condição B, o culturante produziu uma nova ficha (tal qual na condição A) ao invés de aparecer o cronômetro regressivo.

- A mensagem "um item escolar foi removido" é exibida na tela do servidor e não na parte que é projetada como tela expandida na TV, assim os participantes não tem acesso a esta mensagem. 

- A mensagem "a tarefa terminou, obrigado por sua participação! Você produziu 0 fichas e 19+0 itens escolares serão doados a uma escola pública" apareceu logo no segundo ciclo na condição B.

[Dados 17-09-2018.zip](https://github.com/lacs-ufpa/free-mtrix/files/2389667/Dados.17-09-2018.zip)

**Comment by cpicanco** [comment]
@damomribeiro , por favor, envie apenas o arquivo de configuração, pois você já confirmou que está tudo ok com os ips. O arquivo zipado está corrompido. Anexe o txt mesmo.

**Comment by damomribeiro** [comment]
Ok, reenviando. 
[damon.txt](https://github.com/lacs-ufpa/free-mtrix/files/2393568/damon.txt)

**Comment by damomribeiro** [comment]
Fiz novos testes, um com 20 ciclos e um menor com 10 e isso voltou a acontecer:
> Ao passar da condição A para a B, a mensagem apareceu com um certo atraso e mais um ciclo da condição A pôde ser concluído., só então passou-se para a condição B. A mensagem deveria aparecer de modo que os participantes não pudessem mais fazer escolhas após seu aparecimento.

Neste teste, por exemplo, a mensagem da condição B não apareceu logo com o fim do ciclo 20, mas só quando já estávamos no ciclo 22. 

> A mensagem "um item escolar foi removido" é exibida na tela do servidor e não na parte que é projetada como tela expandida na TV, assim os participantes não tem acesso a esta mensagem.

![img_20180920_154957667_burst010](https://user-images.githubusercontent.com/39706036/45844582-411b8000-bcf9-11e8-8220-0b072ae977c5.jpeg)
Devido ao uso da tela expandida as mensagens estão sendo exibidas na tela do servidor, mas não na parte da tela que é projetada para os participantes. 

A sessão continua se encerrando pouco depois da condição B começar, nesse caso encerrou no ciclo 25. Os itens não foram contabilizados no final (mas acho que você já tinha apontado que estava fazendo as correções nesse ponto)
![img_20180920_161738910_hdr](https://user-images.githubusercontent.com/39706036/45844727-ac655200-bcf9-11e8-9e0e-f95502037686.jpeg)

Obrigado!

**Comment by damomribeiro** [comment]
@cpicanco lembrei de mais uma coisa, o timer está aparecendo com cerca de dois segundos de atraso após a ocorrência do culturante.

**Comment by cpicanco** [comment]
@damomribeiro 

> Fiz novos testes, um com 20 ciclos e um menor com 10 e isso voltou a acontecer:

De fato, não consegui replicar sua observação.

> A mensagem "um item escolar foi removido" é exibida na tela do servidor e não na parte que é projetada como tela expandida na TV, assim os participantes não tem acesso a esta mensagem.

A mensagem verde está sendo apresenta a todos os participantes em suas respectivas telas. Fiz com que a mesma mensagem, contudo em tela cheia e sem o fundo verde, também seja apresentada na tela dos contadores.

> A sessão continua se encerrando pouco depois da condição B começar, nesse caso encerrou no ciclo 25. 

Não consegui replicar sua observação. O critério de finalização de uma condição é determinado pelas suas respectivas chaves no arquivo de configuração `Critério_de_Finalização`;

```
"Recomendo aumentar o número de ciclos por condição mudando o valor da configuração Critério_de_Finalização.Ciclos para algo maior do que dois:"

[Condição.1]
Nome=Condição A1
Rodada.NúmeroDeJogadores=3
Pontos.Somar_ao_iniciar_condição.A=0
Pontos.Somar_ao_iniciar_condição.B=0
Pontos.Somar_ao_iniciar_condição.I=0
Pontos.Somar_ao_iniciar_condição.G1=0
Pontos.Somar_ao_iniciar_condição.G2=0
Ciclos.MudançaDeGeração=410
Critério_de_Finalização.Estilo=CICLOS

; modifique o número de ciclos por condição alterando o número
Critério_de_Finalização.Ciclos=2

Critério_de_Finalização.Porcentagem=80,10

```
[experiment_runner_windows_32bits_v0.2.0.14-26-g75939a5.zip](https://github.com/lacs-ufpa/free-mtrix/files/2408919/experiment_runner_windows_32bits_v0.2.0.14-26-g75939a5.zip)

**Comment by cpicanco** [comment]
@damomribeiro 
> lembrei de mais uma coisa, o timer está aparecendo com cerca de dois segundos de atraso após a ocorrência do culturante.

Eu reduzi o valor interno referente ao tempo de apresentação entre mensagens para um segundo. Remover o tempo entre as mensagens no momento não será viável, pois o programa não foi pensado para isso.

**Comment by damomribeiro** [comment]
> De fato, não consegui replicar sua observação.

Acredito que como você deve estar fazendo o teste em um só computador a velocidade das escolhas seja diferente de quando simulamos aqui usando os três computadores para fazer as escolhas.

Penso que, como estamos fazendo os testes usando os três computadores, conseguimos fazer as escolhas mais rapidamente, simulando bem como os participantes farão. No último ciclo da condição A, logo a pós a resposta do P3, o P1 faz a escolha imediatamente depois de P3, ou seja, mesmo antes de aparecer a mensagem de mudança de ciclo ele (P1) consegue fazer a escolha e apertar confirma. A mensagem que marca a mudança da condição está aparecendo mais ou menos quando o P2 está fazendo sua escolha, sendo assim, mesmo quando a tela muda para a condição B, um ciclo nos moldes da condição A parece ainda estar sendo executado.

Nos testes que fiz, quando isso ocorreu, o primeiro culturante da condição B faz aparecer o timer, mas este some ainda antes de zerar. 

O P1 teria que ficar impossibilitado de responder logo que o p3 fizesse sua ultima escolha na condição A.

Espero que tenha ficado compreensível.

**Comment by cpicanco** [comment]
Compreendi Damon, contudo, nesse momento, não tenho condições de controlar
de forma tão minunciosa os tempos por limitações na maneira como o programa
foi escrito.

**Comment by damomribeiro** [comment]
@cpicanco, só detalhando melhor o erro que tem acontecido:

O problema ocorre quando é chega ao último ciclo definido para a primeira condição e o P1 faz a escolha logo em seguida à escolhao P3, se o P1 fizer a escolha durante ou mesmo antes da aparição da mensagem de mudança de condição então o cronômetro da condição B apresenta um comportamento inesperado, ele aparece com atraso e desaparece antes de chegar a zero.

**Comment by cpicanco** [comment]
@damomribeiro , há uma nova versão em anexo. Nessa versão as mensagens em tela cheia apresentadas na tv também são apresentadas em tela cheia na tela dos participantes. Ao final de uma condição, se o valor for de itens for igual a zero, a condição é encerrada no ciclo seguinte (no momento não é possível forçar a passagem de uma condição, a passagem da condição depende das jogadas dos participantes).

[experiment_runner_windows_damon.zip](https://github.com/lacs-ufpa/free-mtrix/files/2466336/experiment_runner_windows_damon.zip)

**Comment by damomribeiro** [comment]
@cpicanco, a mensagem nas telas dos participantes funcionou muito bem pra evitar os problemas que ocorriam na condição B. Houve uma vez em que o contador parou de subtrair os itens mesmo com a mensagem aparecendo, mas testei mais algumas vezes e não voltou a acontecer. Muito bom mesmo. 

> no momento não é possível forçar a passagem de uma condição

Ok, fico no aguardo.

Muito obrigado pela atenção.

**Comment by cpicanco** [comment]
>        no momento não é possível forçar a passagem de uma condição
> Ok, fico no aguardo.

Você não deve aguardar Damon, essa funcionalidade não será implementada em
tempo hábil. Eu contornei o problema da forma como eu descrevi
anteriormente.

**Comment by damomribeiro** [comment]
@cpicanco a nova versão corrigiu bem os bugs. Muito obrigado.

Gostaria de saber se editando o arquivo txt do experimento é possível tirar a mensagem de texto **"vocês nem doaram e nem retiraram itens escolares"** que aparece na condição B. Caso seja algo possível apenas reescrevendo o programa você poderia retirá-la?

**Comment by cpicanco** [comment]
@Damon, anexe o arquivo de configuração mais recente aqui

**Comment by damomribeiro** [comment]
Segue, em anexo: [damom 3.txt](https://github.com/lacs-ufpa/free-mtrix/files/2496720/damom.3.txt)

**Comment by cpicanco** [comment]
Damon, de fato havia um erro lógico que impedia desabilitar as mensagens de metacontingências. Tudo o que você precisa fazer é retirar o código `MENSAGEM` da consequência da metacontingência alvo. A seguir você pode conferir um exemplo para metacontingência 4 do seu arquivo de configuração:

```
; com mensagem
Metacontingência.4.Consequência=0,0|MENSAGEM,

; sem mensagem
Metacontingência.4.Consequência=0,0|,

```

Há uma nova versão em anexo:

[experiment_runner_windows_damon.zip](https://github.com/lacs-ufpa/free-mtrix/files/2508790/experiment_runner_windows_damon.zip)

**Comment by damomribeiro** [comment]
Testei a nova versão, @cpicanco. Funcionou muito bem.
Obrigado.
