### ISSUE TITLE
Free-Mtrix e macrocontingência

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#39]
Boa tarde Rafael, estou com algumas dúvidas relativas ao programa.
1- Baixei o GitHub e o Lazarus. Clonei a pasta Free Mtrix do site para o GitHub Desktop. Consegui abrir o Design no Lazarus, mas não sei editar. Consegui abrir o Runner, mas não tem programação, então não roda nada, apesar de abrir. 

2- Tentei também o arquivo Designer ([persistence.txt](https://github.com/lacs-ufpa/free-mtrix/files/2233450/persistence.txt)), sendo que neste consigo programar contingências e metacontingencias, mas ao abrir o Runner, continua igual ao descrito no ponto 1. 

3- Ainda que consiga programar e rodar no Runner, resta a dúvida sobre como editar o programa para que seja possível programar contingências não entrelaçadas. No caso seriam apenas escolhas de linhas pares ou ímpares e variações em reservas de itens. A ideia era ficar com esta interface:

![image](https://user-images.githubusercontent.com/36678200/43285747-518332d2-90f6-11e8-85e1-800388d3359c.png)

Nesse caso preciso alterar para que fique com 8 linhas e alterar os contadores. 

Então os participantes escolhem simultaneamente e de forma independente. Não há contingências entrelaçadas programadas. Na condição A, por exemplo, linhas ímpares produzem 3 fichas para o indivíduo (acrescenta no contador individual), e uma subtração de 3 fichas da reserva de fichas (subtrai do contador "reserva de fichas"). Na condição B é semelhante, mas na C a diferença é de que as escolhas entre pares e ímpares subtraem nas duas reservas simultaneamente. 

Até logo,
obrigado!!

**Comment by cpicanco** [comment]
Davi, não há necessidade de você editar o programa. Mas você pode estar
querendo aprender a editá-lo. Por favor, confirme para mim se você quer
aprender a editar o programa.

Podes confirmar para mim qual a data prevista para a tua coleta?

**Comment by daviddelimarabelo** [comment]
Caso não seja necessário editar, como eu poderia usar ele para este procedimento que lhe mostrei? Tenho interesse em aprender a editar se for viável em termos de tempo. A previsão é de que seja neste ano, o mais breve, mas depende do tempo de finalização do software.
