### ISSUE TITLE
O comando "Salvar como" não está intuitivo

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/free-mtrix#4]
Dois planejamentos de experimentos (Estudo 1 e Estudo 2) foram salvos através do campo "Salvar como", porém, depois do procedimento de salvar, ao solicitar a abertura do planejamento do Estudo 1, através do campo "Abrir", foram apresentadas as mesmas nomeações e configurações do Estudo 2 (que estava aberto), como se não tivesse salvado o planejamento do experimento do Estudo 1.

**Comment by cpicanco** [comment]
Os arquivos foram salvos no mesmo local ou em locais diferentes? (acho que na mesma pasta né?)

**Comment by cpicanco** [comment]
Já sei o que aconteceu. A lógica do programa não está intuitiva, pois todas as modificações são salvas diretamente no arquivo original e não um arquivo auxiliar. Você deve salvar a segunda cópia antes de realizar qualquer alteração.

**Comment by thaismguimaraes** [comment]
Salvei o primeiro planejamento, em cima dele fui construindo o segundo planejamento e salvei como.

**Comment by cpicanco** [comment]
Exatamente. Não está intuitivo (como num arquivo de word por exemplo). Você deve primeiro salvar uma copia e depois modificar. Vou pensar em como melhorar isso. Mas está salvando sim.

**Comment by thaismguimaraes** [comment]
Ok. Obrigada. =)

**Comment by cpicanco** [comment]
Compreendo a necessidade de melhoria do comando "salvar como". Isso poderá ser resolvido em outro momento.
