### ISSUE TITLE
Fluxograma - David

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#40]
Ver adiante.

**Comment by cpicanco** [comment]
Égua David, me descupe por essa resposta atrasada. Vou conferir o fluxograma e te dou um retorno ainda hoje.

**Comment by daviddelimarabelo** [comment]
Tudo bem, fiz em ppt mesmo, se tiver dúvida só dizer. 
Obrigado!

**Comment by cpicanco** [comment]
Olá David, por favor, teste a versão em anexo. Para a apresentação dos itens, fichas e reservas optei por usar o mesmo modelo do Damon. Tudo na televisão. O participante tem contato com as mensagens em seu próprio monitor, porém os itens são apresentados na tela da televisão.

Qualquer coisa é só falar. Estou enviando um arquivo de configuração para você testar o programa. Lembre-se, você pode testá-lo em um único computador. Mas se for possível dois monitores irá facilitar sua vida.

[experiment_runner_windows_32bits_v0.2.0.14-27-gc433d27.zip](https://github.com/lacs-ufpa/free-mtrix/files/2436142/experiment_runner_windows_32bits_v0.2.0.14-27-gc433d27.zip)

**Comment by cpicanco** [comment]
@daviddelimarabelo

**Comment by cpicanco** [comment]
@daviddelimarabelo , por favor, teste essa versão.

[experiment_runner_david.zip](https://github.com/lacs-ufpa/free-mtrix/files/2465595/experiment_runner_david.zip)

**Comment by cpicanco** [comment]
@daviddelimarabelo , por favor, teste a versão em anexo. #45

[experiment_runner_windows_david.zip](https://github.com/lacs-ufpa/free-mtrix/files/2466369/experiment_runner_windows_david.zip)

**Comment by cpicanco** [comment]
@daviddelimarabelo , por favor, teste a versão em anexo. #46 

[experiment_runner_windows_david.zip](https://github.com/lacs-ufpa/free-mtrix/files/2473920/experiment_runner_windows_david.zip)

**Comment by cpicanco** [comment]
Olá @daviddelimarabelo , o que deve acontecer com a reserva de uma condição ao longo do experimento? Somada?

**Comment by daviddelimarabelo** [comment]
Prezado @cpicanco a reserva deve ser reiniciada ao valor inicia de 200 unidades a cada nova condição. Contudo, é preciso registrar para o experimentador a quantidade de unidades restantes, na reserva, ao final de cada condição.

Obrigado.

**Comment by daviddelimarabelo** [comment]
Prezado @cpicanco gostaria apenas de confirmar dois pontos importantes, sendo um uma sugestão recente do Aécio. 

1. A reserva é alterada a cada jogada, de forma que a subtração do valor ocorra imediatamente após a escolha de cada participante. 

2. Quando o terceiro participante tiver escolhido, e houver sido subtraído o valor correspondente na reserva aparece um aviso na tela comum escrito "REAJUSTE". Após 1 segundo desse aviso a reserva é reajustada. 

As alterações foram feitas no fluxograma, e indicadas com a cor vermelha. O fluxograma com as alterações está em anexo

Obrigado. 
[Fluxograma.pptx](https://github.com/lacs-ufpa/free-mtrix/files/2559065/Fluxograma.pptx)

**Comment by daviddelimarabelo** [comment]
Prezado @cpicanco , o experimento terá a microcultura ABC e a BAC. Para alterar a ordem das condições basta modificar o arquivo de texto do programa?

Grato.
David.

**Comment by cpicanco** [comment]
Isso, basta alterar a numeração e o nome das condições

Rafael

**Comment by cpicanco** [comment]
Há uma nova versão em anexo @daviddelimarabelo 
[experiment_runner_windows_32bits_v0.2.0.14-28-g8268fbd.zip](https://github.com/lacs-ufpa/free-mtrix/files/2592415/experiment_runner_windows_32bits_v0.2.0.14-28-g8268fbd.zip)

**Comment by daviddelimarabelo** [comment]
Prezado @cpicanco , sobre a v0.2.0.14-28 do runner, testamos e notamos alguns pontos que precisam de ajustes.

1. O critério de mudança de condição é de chegar a 306 unidades ou 0 unidades nas reservas de fichas ou de itens, em qualquer das condições. Conversei com Aécio sobre o critério de apenas ciclos. Observamos que para esta pergunta de pesquisa em específico, referente ao efeito cumulativo no uso de recursos esgotáveis, o critério de mudança de condição adequado é o de quantidade de recursos. O critério de ciclos modifica o problema de pesquisa, sendo incoerente teoricamente.

2. Os valores restantes na reserva de fichas nas condições A e C serão distribuídas entre os três participantes ao final do experimento. Para isso, sugerimos um modelo de organização da interface, de acordo com essa imagem:

![image](https://user-images.githubusercontent.com/36678200/48799426-d9c48100-ece5-11e8-8140-de623bc348b4.png)

                        a. Nessa imagem o texto no canto inferior direito, marcado com a seta laranja, ficará disponível na tela da televisão ao longo das três condições. Os "itens produzidos anteriormente" referem-se aos itens restantes na reserva de itens na condição anterior (quando for aplicável) e "reserva coletiva para divisão" refere-se às fichas restantes na reserva de fichas na condição anterior (quando for aplicável). No delineamento ABC, o valor restante na reserva de fichas na condição A será acrescentado a "reserva coletiva para divisão", ao iniciar a condição B, enquanto "itens produzidos anteriormente" ficará zerado. Ao iniciar a condição C, o valor restante na reserva de itens na condição B será acrescido ao "itens produzidos anteriormente", enquanto a "reserva coletiva para divisão" ficará com o mesmo valor inicial da condição B. O mesmo vale para o delineamento BAC, com as respectivas modificações. Ao final do experimento, o valor restante na reserva de fichas e de itens serão adicionadas "reserva coletiva para divisão" e "itens produzidos anteriormente". A reserva coletiva para divisão será distribuída igualmente entre os três participantes, e adicionado aos valores produzidos individualmente. Na mensagem final deve aparecer o valor individual de fichas e os itens escolares produzidos.

3. A renovação do valor das reservas de fichas e itens está ocorrendo na segunda jogada, e não após a terceira. É necessário que após a terceira jogada o participante possa ver que o valor produzido individualmente foi subtraído da reserva, e que após as três escolhas houve um reajuste.

4. Na vez em que rodei, o participante 2 escolheu duas vezes seguidas. Quando isso ocorre o participante 2 não joga na rodada seguinte. 

5. Aécio orientou para mudar o nome "reserva de fichas" por "fichas coletivas".

Obrigado!

**Comment by cpicanco** [comment]
Olá @daviddelimarabelo, sobre o ponto 1. Não basta ter relevância teórica, a investigação de um problema também deve ser exequível. Portanto, além de não haver qualquer incoerência devidamente descrita, alerto para o fato de que novas alterações no sistema de critérios não são triviais e podem comprometer a exequibilidade do seu estudo. Adicionalmente, retirar o número fixo de ciclos possui como consequência direta a tendência de aumento do tempo de duração dos experimentos, o que também compromete a exequibilidade do estudo.

**Comment by cpicanco** [comment]
Sobre o seu ponto 3:

> A renovação do valor das reservas de fichas e itens está ocorrendo na segunda jogada, e não após a terceira. É necessário que após a terceira jogada o participante possa ver que o valor produzido individualmente foi subtraído da reserva, e que após as três escolhas houve um reajuste.

De acordo com o fluxograma, a subtração de fichas deve acontecer após cada jogada e o reajuste após a terceira jogada. É exatamente isto que está acontecendo. Você está considerando o fato de que a ordem de jogadas é aleatória?

**Comment by daviddelimarabelo** [comment]
> Olá @daviddelimarabelo, sobre o ponto 1. Não basta ter relevância teórica, a investigação de um problema também deve ser exequível. Portanto, além de não haver qualquer incoerência devidamente descrita, alerto para o fato de que novas alterações no sistema de critérios não são triviais e podem comprometer a exequibilidade do seu estudo. Adicionalmente, retirar o número fixo de ciclos possui como consequência direta a tendência de aumento do tempo de duração dos experimentos, o que também compromete a exequibilidade do estudo.

Prezado @cpicanco , sobre a incoerência teórica observamos que o critério de mudança de condição baseado apenas na quantidade de ciclos modifica o problema de pesquisa da seguinte forma: a possibilidade de esgotamento dos recursos é a questão no dilema dos comuns, e ao priorizar a mudança de ciclos em detrimento da quantidade de recursos como critério de mudança de condição implica na impossibilidade dos participantes lidarem com o esgotamento, dado que os recursos ficariam negativos e, mesmo assim, continuariam respondendo "retirando" da reserva coletiva. Buscamos avaliar os efeitos da natureza dos produtos cumulativos sobre respostas de retirada de recursos comuns, quando esgotáveis. A possibilidade de responder por 100 ciclos, ainda que não haja mais recursos disponíveis, distorce a finalidade do experimento e destoa das outras pesquisas que utilizaram procedimentos semelhantes. Nesse experimento não há necessidade de prolongar a condição quando as escolhas dos participantes não produzem mais efeitos sobre a reserva comum (após zerar não há mais renovação nem decréscimo, assim como após aumentar até 306 unidades não há mais a possibilidade de esgotamento). Quanto ao tempo, o experimento duraria no máximo 100 ciclos, já que haveria tanto o critério de 100 ciclos máximos quanto o de quantidade de recursos, de forma que não haveria aumento no tempo de duração do experimento.

Obrigado!

**Comment by daviddelimarabelo** [comment]
> No campo "itens produzidos anteriormente" o valor é um somatório de todas as condições anteriores?
> Sim, somatório do que restou na reserva comum de itens nas condições anteriores.
> No campo "Reserva coletiva para divisão" o valor é um somatório de todas as condições anteriores?
> Sim, o somatório do que restou na reserva comum de fichas nas condições anteriores.
> Sobre o ponto quatro, eu não consegui reproduzir esse problema. Por favor, me envie o arquivo de dados do teste no qual você observou tal problema:
> Vou recuperar o arquivo após liberarem os computadores dos experimentos e lhe envio, mas o problema parece estar na aleatoriedade das escolhas.
> Em sintonia com a proposta de Aécio de renomear "Reserva de fichas" para "Fichas coletivas", recomendo renomear "Reserva coletiva para divisão" para "Total de fichas coletivas para divisão". Recomendo renomear "itens produzidos anteriormente" para "Total de itens para doação", pois os itens não foram produzidos, eles foram acumulados e serão doados.
> Correto, concordo.

**Comment by aecioborba** [comment]
Prezado @cpicanco : 

David me encaminhou as preocupações demonstradas anteriormente por você sobre os critérios de encerramento das condições do estudo. 

Os critérios devem incluir um número máximo de ciclos como sugerido (p. ex, 100 ciclos), mas é essencial que haja também como critérios de encerramento o esgotamento do recurso (que pode ocorrer desde 35 a 100 ciclos), ou de atingir um teto (que pode acontecer de 25 a 100 ciclos). O número de ciclos que leva para atingir esses níveis, bem como a curva de acumulação ou esgotamento, são algumas de nossas variáveis dependentes, de forma que o estudo não deve limitar o número de ciclos a priori. Isso é essencial tanto para cumprir o efeito do fenômeno que estamos analisando (esgotamento de recursos) quanto para dialogar com a literatura que trabalha com esse tipo de fenômeno.

Sendo assim, gostaria de saber se é possivel incluir esses critérios sem que haja um impacto de reestruturação do software que já existe, ou você recomenda que "usemos a criatividade" para usar esses critérios sem precisar modificar a estrutura do sistema - por exemplo, pausando manualmente no momento em que os recursos atinjam os níveis de foco (máximo ou esgotamento).

Abraço,

Aécio

**Comment by cpicanco** [comment]
Olá @aecioborba , bem vindo ao projeto Free-mtrix. A minha recomendação à você, tal como desenvolvida a seguir, considera que os processos comportamentais após 306 ou 0 itens constarem no contador de recursos não são relevantes para o projeto do David. Permita-me tentar esclarecer a questão dos critérios com um pouco de matemática. Considere as seguintes condições:

- você estabelece 306 como máximo de items na reserva
   1. 3 itens da reserva são retirados antes do reajuste de 3% a cada ciclo
   1. 5 itens da reserva são retirados antes do reajuste de 3% a cada ciclo
   1. 7 itens da reserva são retirados participantes, desde o início, retiram apenas 6 itens da reserva e um participante retira apenas 2 antes do reajuste de 3% a cada ciclo
   1. três participantes, desde o início, retiram apenas 9 itens da reserva antes do reajuste de 3% a cada ciclo
Ora, se todos sempre retiram apenas 3 itens antes de um reajuste de 3%, então a duração máxima do experimento nessas condições é de 29 ciclos.

**Comment by daviddelimarabelo** [comment]
Prezado @cpicanco , quanto aos ajustes que podem ser feitos dentro desse prazo, sintetizando vimos que podem ser realizados:

1. Renomear "reserva de fichas" para "fichas coletivas".
2. Renomear "reserva coletiva para divisão" para "total de fichas coletivas para divisão"
3. Renomear "itens produzidos anteriormente" para "total de itens para doação".
4. Adicionar o contador "total de fichas coletivas para divisão".
5. Adicionar o contador "total de itens para doação".
6. Corrigir a ordem do reajuste (após a terceira jogada do ciclo).
7. Randomizar de forma que a ordem de jogadas em cada ciclo seja sempre diferente da anterior.
8. Incluir a pausa manual.

Há algum destes que não será possível realizar ou há algum que possa ser incluído?

Obrigado pela disponibilidade e atenção!

**Comment by cpicanco** [comment]
@daviddelimarabelo , uma nova versão está em anexo.

Essa versão inclui ajustes e correções:

1. correção de bugs na ordem de aplicação do efeito cumulativo;
2. modificações no texto dos rótulos dos contadores;
3. adicão de dois novos contadores;
4. registro dos valores acumulados a cada condição (ver arquivo do chat).
5. critério misto de máximo (306), mínimo (0) e número de ciclos (de acordo como definido no arquivo de configuração).

Sobre o critério misto, devo esclarecer que por problemas internos (complexidade e legibilidade atual do programa) não foi possível fazer uma verificação turno à turno de cada critério. Estou fazendo a verificação ciclo à ciclo. Isso significa que internamente valores acima de 306 e abaixo de zero são possíveis durante o ciclo de aplicação do critério. Porém, não é possível visualizar valores abaixo de zero nos contadores o que reduz a chance de os participantes serem afetados por isso (possivelmente).

[experiment_runner_windows_32bits_v0.2.0.14-31-g128d748.zip](https://github.com/lacs-ufpa/free-mtrix/files/2660091/experiment_runner_windows_32bits_v0.2.0.14-31-g128d748.zip)

**Comment by daviddelimarabelo** [comment]
Prezado @cpicanco , seria possível, dentro dos limites de tempo e da complexidade do programa, fazer com que a retirada da reserva seja feita apenas após a jogada do terceiro participante? Nesse caso o ciclo seria: o participante escolhe e produz a consequência individual, o segundo participante escolhe, e depois o terceiro. Após o terceiro escolher e produzir a consequência individual, aparece a mensagem de "vocês retiraram" indicando quanto os três juntos retiraram da reserva, e daí esse valor é subtraído da reserva. Planejamos coletar amanhã à tarde, em função da disponibilidade dos estudantes no fim de ano. Caso não seja possível, tentaremos usar a coleta manual.

Obrigado!
