### ISSUE TITLE
Ciclos sem ordem

### ISSUE THREAD

**Issue by damomribeiro** [lacs-ufpa/free-mtrix#41]
@cpicanco os ciclos nesse experimento precisam ter uma configuração diferenciada, sem ordem predefinida ou mesmo aleatória. 

O ideal aqui seria que que cada um dos participantes pudessem **fazer escolhas ao mesmo tempo e o ciclo seja computado quando todos tiverem feito suas escolhas**. 

Isso é necessário especialmente devido à condição B na qual a velocidade do entrelaçamento tem relação direta com a manutenção ou não dos itens.

**Comment by cpicanco** [comment]
Damon, a ordem dos participantes pode ser randômica. Contudo, atualmente
não existem rodadas simultâneas, apenas rodadas sucessivas.

Preciso conferir a viabilidade de implementar essa funcionalidade em tempo
hábil.

**Comment by cpicanco** [comment]
Confirme para mim se você precisará do registro da latência das respostas.

**Comment by damomribeiro** [comment]
Não preciso. Conversei com Thais e Yan e consideramos que não seriam dados relevantes pra o objetivo dessa pesquisa.

**Comment by cpicanco** [comment]
Sobre a ordem dos ciclos, basta colocar a seguinte linha na seção de cada condição para que a ordem dos ciclos naquela condição seja randômica:

```
Rodada.OrdemDeJogadaAleatória=1
```
