### ISSUE TITLE
Remoção de itens escolares

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#42]
Prezado @cpicanco, testamos o software e verificamos que está aparecendo a mensagem de que foram removidos itens escolares, e permanece o contador ao lado dos itens escolares (como no do Damom). Neste não há contador, e não há remoção de itens escolares da forma como está ocorrendo.

Obrigado

**Comment by cpicanco** [comment]
Olá David, 

https://github.com/lacs-ufpa/free-mtrix/blob/david/experiment_runner/form_matrixgame.pas

O código correspondente à remoção de itens escolares foi removido (até aonde eu sei). Portanto deve estar havendo algum engano. Podes confirmar se você usou a versão que eu enviei à você?

**Comment by daviddelimarabelo** [comment]
Olá, sim usei aquela versão que enviastes. No texto não há perda de itens, mas a mensagem aparece após um tempo fixo, independente das respostas.

**Comment by cpicanco** [comment]
Você não está usando a versão correta do programa.
