### ISSUE TITLE
Programação de efeitos cumulativos

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#43]
Prezado @cpicanco, verificamos que as contingências operantes programadas está funcionando bem, mas faltam os efeitos cumulativos (reservas de itens e de fichas). Na condição A deve constar a quantidade de fichas disponíveis na reserva, na B a quantidade de itens disponíveis na reserva, e na C haver as duas. É possível mudar isso apenas modificando o arquivo de texto?

Obrigado!

**Comment by cpicanco** [comment]
Olá David, 

https://github.com/lacs-ufpa/free-mtrix/blob/david/experiment_runner/form_points.pas#L148-L179

O efeito cumulativo é controlado pelo nome da condição:

https://github.com/lacs-ufpa/free-mtrix/blob/david/experiment_runner/form_points.pas#L136-L146

Condição 1:
    Condição A1 ou
    Condição A2 ou
    Condição A3 

Condição 2:
    Condição B1 ou
    Condição B2 ou
    Condição B3

Condição 3:
    Condição C1 ou
    Condição C2 ou
    Condição C3

**Comment by daviddelimarabelo** [comment]
Acho que entendi. Nesse caso já está programado, mas ainda não aparece? Como alterar o arquivo de texto para adicionar as reservas, seus contadores e sua variação e reajuste?

[Experimento]
Pesquisador.Nome=David Lima
Nome=Effects of the Nature of Common Pool Resources in Ethical Self-Control
Objetivo= Avaliar o efeito do efeito cumulativo no nível cultural sobre o comportamento dos participantes de microculturas de laboratório.
Jogadores.Novos.Enviar_Histórico_do_BatePapo=0
Jogadores.GerarAutomaticamente=0
Pesquisador.PodeJogar=0
Pesquisador.BatePapo=0
Jogadores.BatePapo=0
TipoDePontuação=1
TipoDaMatrix=CORES,LINHAS,

[Condição.1]
Nome=Condição A1
; MensagemInicial=Mensagem1
Rodada.NúmeroDeJogadores=3
Ciclos.MudançaDeGeração=200
Critério_de_Finalização.Estilo=CICLOS
Critério_de_Finalização.Ciclos=5

Contingência.1.Nome=Impar
Contingência.1.Resposta=IMPAR,|LINHAS||
Contingência.1.Consequência=1,0|MENSAGEM,MENSAGEM A TODOS,PONTOS,PONTOS I,
Contingência.1.Consequência.Mensagem.Prefixo=$NICNAME ganhou 1 ficha.

Contingência.2.Nome=Par
Contingência.2.Resposta=PAR,|LINHAS||
Contingência.2.Consequência=3,0|MENSAGEM,MENSAGEM A TODOS,PONTOS,PONTOS I,
Contingência.2.Consequência.Mensagem.Prefixo=$NICNAME ganhou 3 fichas.

[Condição.2]
Nome=Condição B1
; MensagemInicial=Mensagem2
Rodada.NúmeroDeJogadores=3
Ciclos.MudançaDeGeração=200
Critério_de_Finalização.Estilo=CICLOS
Critério_de_Finalização.Ciclos=5

Contingência.1.Nome=Impar
Contingência.1.Resposta=IMPAR,|LINHAS||
Contingência.1.Consequência=1,0|MENSAGEM,MENSAGEM A TODOS,PONTOS,PONTOS I,
Contingência.1.Consequência.Mensagem.Prefixo=$NICNAME ganhou 1 ficha.

Contingência.2.Nome=Par
Contingência.2.Resposta=PAR,|LINHAS||
Contingência.2.Consequência=3,0|MENSAGEM,MENSAGEM A TODOS,PONTOS,PONTOS I,
Contingência.2.Consequência.Mensagem.Prefixo=$NICNAME ganhou 3 fichas.

[Condição.3]
Nome=Condição C1
; MensagemInicial=Mensagem3
Rodada.NúmeroDeJogadores=3
Ciclos.MudançaDeGeração=200
Critério_de_Finalização.Estilo=CICLOS
Critério_de_Finalização.Ciclos=5

Contingência.1.Nome=Impar
Contingência.1.Resposta=IMPAR,|LINHAS||
Contingência.1.Consequência=1,0|MENSAGEM,MENSAGEM A TODOS,PONTOS,PONTOS I,
Contingência.1.Consequência.Mensagem.Prefixo=$NICNAME ganhou 1 ficha.

Contingência.2.Nome=Par
Contingência.2.Resposta=PAR,|LINHAS||
Contingência.2.Consequência=3,0|MENSAGEM,MENSAGEM A TODOS,PONTOS,PONTOS I,
Contingência.2.Consequência.Mensagem.Prefixo=$NICNAME ganhou 3 fichas.

**Comment by cpicanco** [comment]
Não é necessário. Os itens ou fichas das reservas iniciam com 200, como
previsto no seu projeto.

Rafael

**Comment by daviddelimarabelo** [comment]
A imagem que aparece para os participantes é esta daqui, onde de um lado tem a quantidade de fichas individuais, abaixo do ícone "fichas", e à direita o ícone "itens escolares" ao lado do contador em 0. Onde vejo a quantidade de 200 para fichas e itens? 

![image](https://user-images.githubusercontent.com/36678200/46737589-4160c880-cc72-11e8-9bc7-31f337051a39.png)

**Comment by cpicanco** [comment]
Este é o programa do Damon, não o seu. Eu devo ter anexado o arquivo errado.

Rafael
