### ISSUE TITLE
Ordem das escolhas

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#44]
Prezado @cpicanco, verificamos também que as escolhas estão ocorrendo sequencialmente, e elas podem ocorrer de forma simultânea, sem ordem definida.

Obrigado!

**Comment by cpicanco** [comment]
O programa ainda não permite escolhas simultâneas. As escolhas são
sucessivas e a ordem pode ser aleatória.

**Comment by daviddelimarabelo** [comment]
Como deixar a ordem aleatória?

**Comment by cpicanco** [comment]
Não é necessário editar o arquivo de configuração, por padrão a ordem das jogas é aleatória:

`Rodada.OrdemDeJogadaAleatória=1`
