### ISSUE TITLE
Contador zerado para itens a serem doados.

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#45]
Prezado @cpicanco , este arquivo que enviou agora está correto, obrigado.

Esta imagem é do final do experimento, e consta 0 itens escolares a serem doados, apesar de ter restado 180 na reserva de itens, como mostra a imagem abaixo. 

![image](https://user-images.githubusercontent.com/36678200/46755580-d0cea180-cc9b-11e8-9f26-6c03366cf53a.png)

![image](https://user-images.githubusercontent.com/36678200/46755868-8dc0fe00-cc9c-11e8-9bee-1da2e6eebba8.png)

**Comment by cpicanco** [comment]
Sim, isso é um bug. Já já resolvo isso.
