### ISSUE TITLE
Contador de itens escolares zerado

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#46]
Prezado @cpicanco , testei a versão mais recente que você enviou. O contador de itens escolares a serem doados permanece zerado do início ao final do experimento.

![image](https://user-images.githubusercontent.com/36678200/46816004-6fb5d500-cd52-11e8-82bd-2c3f062b3752.png)

**Comment by cpicanco** [comment]
O que deve acontecer com o contador de itens escolares ao longo do
experimento?

**Comment by daviddelimarabelo** [comment]
Durante o experimento ele não precisa aparecer, pois a própria reserva de itens já indica a quantidade que será doada. Seria necessário apenas ao final, indicando a quantidade de fichas produzidas individualmente e a quantidade de itens que serão doados.

**Comment by cpicanco** [comment]
Que tal manter a correspondência entre o valor da reserva e número de itens
a serem doados (Reserva = Itens a serem doados)? Fica mais claro.

**Comment by daviddelimarabelo** [comment]
Ficaria melhor mesmo, concordo. No lugar de "reserva de itens" fica "itens escolares a serem doados".
