### ISSUE TITLE
Programa travando na condição B

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#48]
Prezado @cpicanco , testei a versão mais recente e funcionou normalmente na maior parte do tempo. Algumas vezes travou durante a condição B, mas ao reiniciar funcionou normalmente. 

Obrigado

**Comment by cpicanco** [comment]
Olá Davi, tente descrever com mais detalhes quando o erro ocorre. Do contrário, ele não poderá ser corrigido.

**Comment by daviddelimarabelo** [comment]
O erro ocorreu duas vezes. Nas duas nenhum dos participates podia selecionar as linhas. Mas farei mais um teste com todas as condições para verificar se há recorrência.
