### ISSUE TITLE
Mudança de condição

### ISSUE THREAD

**Issue by daviddelimarabelo** [lacs-ufpa/free-mtrix#49]
Prezado @cpicanco , testando a versão mais recente notamos que o critério de mudança de condição "quantidade na reserva" (máximo de 306 e mínimo de 0) não funcionou, havendo apenas o critério "finalização de ciclos" (100).

**Comment by cpicanco** [comment]
O seu fluxograma não especificou nenhum critério de finalização das condições. Somente o critério baseado no número de ciclos está funcional.

**Comment by daviddelimarabelo** [comment]
Como fazer para adicionar tais critérios?

**Comment by cpicanco** [comment]
Atualize seu fluxograma.

**Comment by daviddelimarabelo** [comment]
Prezado @cpicanco , atualizei o fluxograma na _Issue #40 _, colocando em vermelho o texto acrescentado.

Obrigado.
