### ISSUE TITLE
Segundo participante não é ativado

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/free-mtrix#5]
Ao executar um experimento teste, não há a solicitação para o pesquisador ativar o segundo participante e  aparece a mensagem que o programa não estar respondendo no computador desse participante. Apenas o primeiro e o terceiro participantes é que são ativados, porém a tarefa não é liberada para ser iniciada.

**Comment by cpicanco** [comment]
Os IPs foram configurados corretamente?

**Comment by thaismguimaraes** [comment]
Conferi isso.
