### ISSUE TITLE
Experimento da Laís

### ISSUE THREAD

**Issue by laismc** [lacs-ufpa/free-mtrix#50]
[Fluxograma_Lais.pptx](https://github.com/lacs-ufpa/free-mtrix/files/2561732/Fluxograma_Lais.pptx)

**Comment by cpicanco** [comment]
Olá @laismc , o tempo de 2 min para fala deve ser apresentado aos participantes? Por exemplo, como uma contagem regressiva?

**Comment by cpicanco** [comment]
O tempo de 2 min para fala deve ser apresentado a cada cinco ciclos, até o final? Ou seja, após esses 2 min, haverá outras oportunidades para fala, de cinco em cinco ciclos?

Se sim, note que a instrução "Após estes 2 minutos não será permitido conversar" é contraditória.

**Comment by laismc** [comment]
Ola, @cpicanco. 
Exatamente, o tempo de 2 min. deve ser apresentado aos participantes como uma contagem regressiva sempre que estiver em vigor. 

Os participantes poderão continuar respondendo durante o tempo de 2 min para fala.

**Comment by cpicanco** [comment]
@laismc , teoricamente é possível que os participantes sejam rápidos e continuem respondendo durante os 2 min para fala. O que deve acontecer se os participantes concluirem 5 ciclos antes do término dos 2 min para fala?

- resetar a contagem regressiva para 2 min ou;
- somar 2 minutos à contagem regressiva em vigor ou;
- outro (descreva) :smile:

**Comment by laismc** [comment]
@cpicanco, são duas contagens diferentes. Quando a contagem regressiva estiver em vigor não há contagem de ciclos. No entanto, a partir do momento em que os 2 minutos esgotam, é inicia a contagem dos 5 ciclos.
Assim, durante os 2 minutos de fala os participantes podem responder a um número irrestrito de ciclos.

**Comment by laismc** [comment]
Oi, @cpicanco.
Estou chegando perto dos meus prazos finais.
Preciso começar minhas coletas na próxima semana, para isso gostaria de testar o software neste final de semana. 
Será possível enviar a primeira versão até sexta? Caso não, pode me dizer o que está faltando para que eu possa pensar na viabilidade de alternativas para o que ainda não está terminado? :)

**Comment by cpicanco** [comment]
Olá Laís, o programa precisa de ajustes na contabilização do efeito
cumulativo. Para confirmar os meus cálculos, você pode me enviar uma
simulação de dois casos? Primeiro iniciando com 200 itens e sempre
retirando 9 e reajustando. Segundo iniciando com 200 e sempre retirando 3 e
reajustando?

Rafael

**Comment by cpicanco** [comment]
@laismc , uma nova versão está em anexo com pequenos ajustes de layout.

[experiment_runner_windows_32bits_v0.2.0.14-38-gd815827.zip](https://github.com/lacs-ufpa/free-mtrix/files/2819772/experiment_runner_windows_32bits_v0.2.0.14-38-gd815827.zip)

**Comment by cpicanco** [comment]
[experiment_runner_windows_32bits_v0.2.0.14-40-gfb1cdf5.zip](https://github.com/lacs-ufpa/free-mtrix/files/2824722/experiment_runner_windows_32bits_v0.2.0.14-40-gfb1cdf5.zip)

**Comment by cpicanco** [comment]
[experiment_runner_windows_32bits_v0.2.0.14-41-g9f34458.zip](https://github.com/lacs-ufpa/free-mtrix/files/2834354/experiment_runner_windows_32bits_v0.2.0.14-41-g9f34458.zip)
