### ISSUE TITLE
Alterações nas mensagens

### ISSUE THREAD

**Issue by damomribeiro** [lacs-ufpa/free-mtrix#51]
@cpicanco gostaria de modificar as mensagens que aparecem durante a condição B do meu experimento:

- "A partir de agora os itens escolares serão subtraídos" para "A partir de agora os itens escolares poderão ser subtraídos"

- "Um item escolar foi removido" para "um item escolar foi subtraído"

Se for possível, modificar também a cor das caixas de diálogo para uma cor mais clara, branco ou próximo disso.

**Comment by cpicanco** [comment]
- A mensagem "A partir de agora os itens escolares serão subtraídos" deve ser alterada no arquivo de sessão
- A mensagem de remoção de itens foi alterada para "Um item escolar foi subtraído."
- As mensagens que antes eram apresentadas na cor `clTeal` são apresentadas agora de acordo com as cores padrão do sistema operacional

Há uma nova versão em anexo:

[experiment_runner_windows_32bits_v0.2.0.14-31-g93a4177.zip](https://github.com/lacs-ufpa/free-mtrix/files/2578704/experiment_runner_windows_32bits_v0.2.0.14-31-g93a4177.zip)

**Comment by damomribeiro** [comment]
@cpicanco, alterei todas as mensagens no arquivo de sessão, mas no momento em que a mensagem "um item escolar foi subtraído" aparece em uma caixa de diálogo ela vem acompanhada da mensagem em tela cheia: "um item escolar foi removido" para todos os participantes.

Esta segunda mensagem deveria ter também a palavra "subtraído" substituída por "removido".

**Comment by cpicanco** [comment]
Em anexo @damomribeiro 

[experiment_runner_windows_32bits_v0.2.0.14-32-g823c147.zip](https://github.com/lacs-ufpa/free-mtrix/files/2591171/experiment_runner_windows_32bits_v0.2.0.14-32-g823c147.zip)
