### ISSUE TITLE
Adição de sons do software

### ISSUE THREAD

**Issue by damomribeiro** [lacs-ufpa/free-mtrix#52]
@cpicanco Após rodar dois pilotos com o software percebemos que as pessoas não têm ficado sob controle das consequências na tela. Os participantes só têm percebido que as consequências foram adicionadas algum tempo depois de terem feito o culturante.

Para tentar corrigir isso gostaríamos de adicionar sons para contingências culturais:
- Bipes para produção de itens escolares
- Perda de itens escolares
- Ativação do timer (CC da condição B1 e B2)
- E redução do tempo do timer por segundo.

Sons diferentes para cada uma delas.

Seria possível adicionar imagens dentro das caixas de diálogos no computador dos participantes? Percebemos que os participantes não estão ficando sob controle das mensagens.

**Comment by cpicanco** [comment]
Embora eu tenha planos de adicionar sons como consequências ao projeto, não terei disponibilidade de implementar essa funcionalidade em tempo hábil para o seu projeto. De qualquer forma, recomendo que você sofistique as instruções aos participantes e reduza o tempo de permanência no experimento ao máximo possível.
