### ISSUE TITLE
Experimento do Yan

### ISSUE THREAD

**Issue by cpicanco** [lacs-ufpa/free-mtrix#53]
# Modificações concluídas

- [x] #15

- [x] #17

- [x] #24

- [x] #25 

- [ ] #26 

- [x] #35 

# Modificações previstas

- [x] #31 

- [x] ajustar sistema de contagem de entrelaçamentos

- [x] ajustar sistema de critério misto de encerramento de condições

Olá @VALDERLON , algumas questões, informes e solicitações:

- por favor, me envie o arquivo de configuração mais recente que você tenha do seu experimento.

- por favor, descreva o critério de encerramento do experimento aqui.

- você precisará que os contadores ora sejam zerados ora sejam somados? O precisará apenas que eles sejam zerados e nada mais?

- você possui mais alguma demanda além das modificações previstas?

- você conseguiu fazer testes usando um único computador?

- você conseguiu fazer os arquivos de configuração de todos os teus delineamentos?

- por questão de agilidade, eu não farei nenhuma modificação ao `designer`. Recomendo que você crie um experimento inicialmente nele, mas em seguida edite apenas o arquivo de texto.

- você tem acompanhado as alterações do experimento de @damomribeiro e @laismc referentes à janela na tv? Note que a versão do programa que serve para o teu experimento hoje não inclui nenhuma dessas alterações.

**Comment by VALDERLON** [comment]
* por favor, me envie o arquivo de configuração mais recente que você tenha do seu experimento.

[Exp LB Atraso e Magnitude BACBAC FINAL.ini.txt](https://github.com/lacs-ufpa/free-mtrix/files/2841312/Exp.LB.Atraso.e.Magnitude.BACBAC.FINAL.ini.txt)

* por favor, descreva o critério de encerramento do experimento aqui.
      O critério de encerramento deveria estar atrelado à frequência de um dos Culturantes prorgamados (qualquer um dos 6, ou os 3 impulsivos ou os 3 autocontrolados). Se não me engano, o programa só consegue fazer pra apenas 1 culturante. Por isso deixamos o critério ser apenas o de 100 ciclos. 

* você precisará que os contadores ora sejam zerados ora sejam somados? O precisará apenas que eles sejam zerados e nada mais?
       Preciso apenas que eles sejam zerados. Sempre que mudar de condição. 

* você possui mais alguma demanda além das modificações previstas?
      Não. O que identifique foram apenas essas duas variáveis principais: zerar os contadores e adicionas os sons à produção de itens. 

* você conseguiu fazer testes usando um único computador?
      Consegui. Tanto usando apenas 1, quanto usando 4 computadores. 

* você conseguiu fazer os arquivos de configuração de todos os teus delineamentos?
     Consegui. Algumas coisas eu fiz com Tide. Mas, no fim das contas, todas as modificações estávamos fazendo no arquivo de texto e todas deram certo. 

* por questão de agilidade, eu não farei nenhuma modificação ao `designer`. Recomendo que você crie um experimento inicialmente nele, mas em seguida edite apenas o arquivo de texto.
        Tudo bem. Creio que já posso fazer diretamente no texto sim.

* você tem acompanhado as alterações do experimento de @damomribeiro e @laismc referentes à janela na tv? Note que a versão do programa que serve para o teu experimento hoje não inclui nenhuma dessas alterações.
       Eu acompanhei. No meu caso, não há necessidade de divisão de tela. Tudo pode ficar na mesma interface (participantes e tv). Entretanto, caso haja necessidade de divisão de telas pra facilitar seu trabalho, é necessário, impreterivelmente, os sons da produção de consequências culturais. 

No mais, fico no aguardo e à disposição. E obrigado pela prestatividade, Rafael.

**Comment by cpicanco** [comment]
@VALDERLON , saco vazio não para em pé. Aguardo ansioso a oportunidade de contribuir com o seu manuscrito, especialmente na descrição do método.

**Comment by VALDERLON** [comment]
@cpicanco , acho muito justo expandirmos essa parceria para outras dimensões desse trabalho, por isso suas contribuições e sugestão serão muito bem aceitas.

**Comment by cpicanco** [comment]
@VALDERLON , há uma versão em anexo. O critério misto (e o sistema de entrelaçamentos subjacente) no seu caso é mais complicado de ser adaptado no momento. Pode demorar. 

[experiment_runner_windows_32bits_v0.2.0.14-27-gf97f6d1.zip](https://github.com/lacs-ufpa/free-mtrix/files/2877847/experiment_runner_windows_32bits_v0.2.0.14-27-gf97f6d1.zip)

**Comment by VALDERLON** [comment]
@cpicanco Muito obrigado pelas alterações. Fiz um teste rápido em apenas um computador com condições de 10 ciclos. O contador está zerando entre as condições, as mensagens estão maiores e mais demoradas. 

Como a matriz e os contadores continuam ambos na mesta tela, imagino que não seja mesmo necessário adicionar os sons. 

No mais, farei outros testes em breve e seguirei com as coletas. 

Novamente, muito obrigado. E quando estivermos em fase de produção textual, podemos avaliar suas considerações e correções. 

Abraço

**Comment by VALDERLON** [comment]
Prezado @cpicanco , 

eu fiz mais dois pilotos com os computadores em rede. Eis o que aconteceu:

1) o som realmente não funciona, mesmo com a configuração de texto estando correta e os arquivos de áudio estarem no formato certo e no local certo. 

2) os participantes relataram que ficaram incomodados com a mensagem das consequências culturais ficarem aparecendo sobre a matriz. Eles disseram que pararam de escolher as linhas 7, 8 e 9 por causa disso. Nesse sentido, queria saber da possibilidade de as mensagens aparecerem no espaço do canto inferior direito do Software. É um espaço que está meio sem uso e creio que isso resolveria o problema. 

Fico no aguardo de suas considerações e agradeceria bastante se forem possíveis essas últimas alterações.

**Comment by cpicanco** [comment]
@VALDERLON , eu precisarei de mais tempo para resolver a questão do som. A localização das mensagens é algo simples de resolver. A mensagem de início mostrada no centro da matriz também deve ser movida para fora da matriz?

**Comment by cpicanco** [comment]
Yan, há uma nova versão em anexo. Eu coloquei a mensagem do item na abaixo da matrix e mantive as outras à direita da matrix.

Eu também fiz uma modificação (que ainda não testei) que imaginei poder corrigir o problema com o som.

[experiment_runner_windows_32bits_v0.2.0.14-29-gf3c882c.zip](https://github.com/lacs-ufpa/free-mtrix/files/2980683/experiment_runner_windows_32bits_v0.2.0.14-29-gf3c882c.zip)

**Comment by cpicanco** [comment]
Yan, há uma nova versão em anexo. Eu coloquei a mensagem do item na abaixo da matrix e mantive as outras à direita da matrix.

Eu também fiz uma modificação (que ainda não testei) que imaginei poder corrigir o problema com o som.

@VALDERLON 

[experiment_runner_windows_32bits_v0.2.0.14-32-ga2bcf16.zip](https://github.com/lacs-ufpa/free-mtrix/files/2984600/experiment_runner_windows_32bits_v0.2.0.14-32-ga2bcf16.zip)

**Comment by VALDERLON** [comment]
@cpicanco Acabei de fazer um teste. Ele abriu, as mensagens estão no local correto. Contudo, o som só funcionou a primeira vez e para apenas um culturante. Ou seja, o som só aconteceu a primeira vez que o culturante impulsivo aconteceu. Nos demais ciclos, o som não acontece. Reabri tudo de novo e fiz primeiro o culturante autocontrolado só para ter certeza e, dessa vez, não teve som nenhum para nenhum dos culturantes. O arquivo de texto está correto, o som esta na pasta e no formato correto.

Fiz isso em um computador só. Mas vou testar em rede. 
OBS: Após abrir o servidor, o runner dos participantes não estava abrindo. Então deletei os arquivos OpenAL32.dll e o wrap_oal.dll Só depois de ter feito isso é que os runners abriram e pude adicionar os participantes. Isso faz diferença no som?

Att
