### ISSUE TITLE
Experimento da Karol

### ISSUE THREAD

**Issue by karol-hora** [lacs-ufpa/free-mtrix#55]
@cpicanco 
Olá! Estou com dificuldade na instalação do software. No Lazarus, usando o menu Executar à Compilar, aparece um erro. 

Erro: O projeto usa SO alvo=Linux e CPU=x86_64.
O “system.ppu” para este alvo não foi encontrada no diretório binário do FPC.
Certifique-se que o FPC está instalado corretamente para este alvo e que “fpc.cfg” contenha os diretórios certos.
experiment_designer
Compilar pacote FCL 1.0.1: Código saída 1, Erros: 1
Fatal: Impossível localizar system usado por fcllaz do pacote FCL

Att

**Comment by cpicanco** [comment]
Olá @karol-hora , bem vinda à comunidade do Free mtrix.

Você está tentando compilar o programa com a build `linux` no windows. Isso não é possível. No windows você deve alternar para a build `win32`.

___

Note que a versão linux do programa é 64bits e essa arquitetura no momento é suportada apenas no Linux. Possivelmente você está tentando executar o programa no windows 10, portanto lembre que no presente momento apenas a versão 32bits é suportada nesse sistema.

Executar o programa não exige instalação no linux, porém no windows depende da instalação dos "Pacotes Redistribuíveis do Visual C++ para Visual Studio 2015" redistribuídos pelo próprio windows. Você pode baixar a versão 32bits do pacote aqui:

https://www.microsoft.com/pt-br/download/details.aspx?id=48145

Após instalar o pacote,  é possível compilar o programa com o Lazarus escolhendo a Build `win32`. Você pode escolher essa build clicando no botão correspondente:

![lazarus-build-button](https://user-images.githubusercontent.com/6511849/61996446-c3d44080-b06a-11e9-983c-ab2922c13674.png)

**Comment by karol-hora** [comment]
Obrigada, @cpicanco 
Consegui instalar. Mas, não estou conseguindo alterar a quantidade de linhas da matriz. Além disso, quando clico para fazer as escolhas, nada acontece (isto é, não há o acréscimo ou a retirada de pontos).

Queria perguntar se há possibilidade de alterar o esquema de reforçamento (nesse caso, torná-lo intermitente) e, além disso, alterar o atraso da apresentação da consequência.

Atenciosamente,

**Comment by cpicanco** [comment]
Olá @karol-hora, eu preciso de mais informações para tentar ajudar você. Você está executando o programa em cada um de um número de computadores em uma rede local ou está executando instâncias do programa em um mesmo computador?

O projeto Free-mtrix inclui dois programas. O `experiment_designer` permite gerar um arquivo de configuração do experimento. Você deve montar um arquivo de configuração base antes de poder executar um experimento. Você deve configurar a rede local de formas diferentes em cada uma dessas duas possibilidades.

O `experiment_runner` permite carregar e executar o arquivo de configuração. Com três participantes definidos no arquivo de configuração do experimento, são necessárias quatro instâncias do programa, seja em uma rede local, seja em um mesmo computador. Uma dessas instâncias funcionará como um servidor (o experimento) e as outras três como clientes (os participantes do experimento). É no servidor que você carrega e executa um arquivo de configuração de um experimento. Após fazer isso o programa entrará em um modo de espera de participantes. Se a sua configuração da rede local estiver certa, após executar uma outra instância do programa na rede, o servidor identificará automaticamente o participante. Quando todos os participantes previstos forem identificados, o experimento é iniciado. Somente a partir desse ponto que a matriz torna-se responsiva. Recomendo que você leia a documentação existente sobre o programa.

Em tese, há a possibilidade de fazer qualquer coisa compreendendo a arquitetura do programa. No momento não há nenhum esquema de reforço intermite implementado. Atrasos nas consequências também não foram implementados. Todas as consequências individuais e culturais são apresentadas imediatamente e continuamente de acordo com os critérios de cada condição experimental. Caso você necessite de orientação em relação a como alterar o código, faça um `fork` do projeto aqui no GitHub. Assim nós dois poderemos modificar o código de forma sincronizada.
