### ISSUE TITLE
Interface do pesquisador

### ISSUE THREAD

**Issue by thaismguimaraes** [lacs-ufpa/free-mtrix#9]
- [x] Os contadores para as pontuações individuais não estão sincronizados, apresentando quantidades diferentes do que realmente os participantes produziram. Isso aconteceu com o contador de ciclos, em um dos testes, porém o contador ao invés de ter quantidade diferente, travou.
- [x] A atualização do Campo do nome da condição está atrasada, só muda após finalizar a condição e mantém a mesmo nome durante a próxima condição. Por ex., durante a Condição 2 aparece o nome da Condição 1, durante a Condição 3 aparece o nome da Condição 2. 
- [x] A contagem dos ciclos também está atrasada, ocorre somente quando finaliza o ciclo. Melhor seria ao iniciar o ciclo, quando o primeiro participante fosse solicitado a escolher a linha. Se possível, ter também um contador de ciclos com o total de ciclos durante o experimento, não somente contabilizar por condição. Bem como, a inserção de um campo com a porcentagem alcançada do critério de mudança durante a condição em vigor.
 
EDIT: 6c4a3ef4520e738ca09327a88a323820c4c56e1b

- [ ] Ao clicar no comando "Pausar" durante o experimento, apareceu uma janela com a mensagem “Não implementado. ”.
- [ ] No campo das informações dos participantes ficou preto, depois vai saindo por partes e aparecendo o conteúdo. Algo parecido aconteceu quando a mensagem para esperar alguém ocupar o lugar não saiu da tela do P2 quando P1 saiu, ficando até o fim (ver Anexo).
![tela do partcipante-issue 8](https://cloud.githubusercontent.com/assets/22668474/22623082/7b6a8482-eb35-11e6-9aed-ec905f85a961.jpg)

**Comment by cpicanco** [comment]
A interface do pesquisador não foi finalizada. A prioridade tem sido a interface dos participantes. Mesmo assim, o bug na caixa "escolhas na última jogada" é novo para mim.

**Comment by thaismguimaraes** [comment]
@cpicanco foi somente na interface do pesquisador.

**Comment by cpicanco** [comment]
@thaismguimaraes , a foto mostra a interface do participante.

**Comment by thaismguimaraes** [comment]
O que está na foto não foi replicado no Teste 2, ocorreu somente no Teste 1. No Teste 2 ocorreu na caixa de "escolhas na última jogada" do pesquisador.
